### ISSUE TITLE
Provide and document how to disable image backup

### ISSUE THREAD

**Issue by jwmatthews** [openshift/oadp-operator#105]
Let's ensure we have a documented configuration of how to disable internal image backup.
This means, do _not_ deploy a registry backed by object storage as a target and do not process internal images beyond default behavior of the yaml manifests.

**Comment by dymurray** [comment]
We want to add a configuration parameter to the Velero CR that disables backup/restore of images entirely. This will require plugin changes as well.

**Comment by dymurray** [comment]
This has been released in 0.3.0 with the flag `backupImages`
