### ISSUE TITLE
Design: TechPreview: Upstream datamover

### ISSUE THREAD

**Issue by weshayutin** [openshift/oadp-operator#1052]
The context of this design is NOT if we should adopt or when, the context would be the technical requirements of including the native velero datamover in OADP.

Upstream Velero is releasing a native datamover in velero 1.12

https://github.com/vmware-tanzu/velero/blob/main/design/volume-snapshot-data-movement/volume-snapshot-data-movement.md
  
* DPA changes
  * pick a datamover  

* From Velero -  Remove OADP 1.2.0 datamover bits
* From OADP -  Remove OADP 1.2.0 datamover bits

* Need to compare OADP 1.2.0 data mover features / functions to native datamover
  *  address gaps
     * if native is missing a feature, create a design upstream
       *  oadp-1.2.0 backup and restore concurrency ( Scott ) 

* Design notes
  * We have one data mover at time??
    *  How is the OADP datamover integrated w/ upstream
      *   
  * Does our OADP datamover integrate into upstream datamover in 1.3.0

  To-do's
- [ ] From Velero - Remove OADP 1.2.0 datamover bits
- [ ] From OADP -  Remove OADP 1.2.0 datamover bits
- [ ] Remove validations for 1.2 DM
- [ ] Remove vsm controller
- [ ] Remove vsm-plugin
- [ ] remove 1.2 dpa parms, add built-in parms
- [ ] Rebase 
- [ ] Need to modify dm e2e test

TO-TEST
- [ ] provision eks in amazon,  
- [ ] do not add vsm plugin to dpa

To Evaluate
- [ ] basic backup / restore w/ csi volumes
- [ ] evaluate what artifacts are left on cluster ( hopefully none )
- [ ] various storage backends, aws, azure, odf, gcp 
- [ ] TTL, ensure velero artifacts are removed, and backups on s3
- [ ] Partner plugin - Shawn
- [ ] VM filesystem mode
- [ ] We suspect enabling kopia as fsb is not required.
- [ ] sts auth, wif auth

**Comment by weshayutin** [comment]
related to #1057

**Comment by shubham-pampattiwar** [comment]
Top of mind I can think of the following (if we want OADP datamover to co-exist with upstream datamover):
- DPA changes would be the configurations needed for DataUpload and DataDownload CRs 
- Integrating with Upstream pluggable datamover interface will involve:
    - Using DataUpload/DataDownload CRs to orchestrate Volsync processes instead of VSB/VSR.
    - Dropping the VSM controller altogether as well as Velero-plugin-for-vsm and rely totally on upstream Datamover controllers and CSI V2 plugin
    - Another train of thought would be to only drop the Velero-plugin-vsm but still rely on VSM controller to trigger datamovement, the flow would be something like plugin -> VSB -> DataUpload CR -> Volsync Replication Source

**Comment by kaovilai** [comment]
directory differences.. instead of bucketRoot/restic, its bucketRoot/kopia and we need to have a migration guide

**Comment by weshayutin** [comment]
@sseago link to design pr?
