### ISSUE TITLE
Need to benchmark performance of OADP plugins and vanilla Velero at scales of ~100k resources per namespace

### ISSUE THREAD

**Issue by jwmatthews** [openshift/oadp-operator#107]
We need to investigate performance improvements when Backing up a single namespace that contains a large amount of resources on order of ~100k.   

See https://github.com/konveyor/openshift-velero-plugin/issues/83 for original details of issue.

When we are ready to setup test environments for benchmarking consider if https://github.com/konveyor/kube-kong-operator can help, we've used this in past to simulate workloads on k8s clusters.

**Comment by dymurray** [comment]
Related: https://github.com/konveyor/oadp-operator/issues/113
