### ISSUE TITLE
Clean up duplicate logic for validating backupstoragelocations and volumesnapshotlocations in dpa

### ISSUE THREAD

**Issue by kaovilai** [openshift/oadp-operator#1129]
https://github.com/kaovilai/oadp-operator/blob/27cccabbd2e845da21ef49489e7506f10c30696d/controllers/validator.go#L19

**Comment by mateusoliveira43** [comment]
Description of the problem:

BSL/VSL are being validated in 3 functions: 
- https://github.com/openshift/oadp-operator/blob/424a33aa0b82bfe24ea7ba94cbfbe9e46180447d/controllers/validator.go#L17
- https://github.com/openshift/oadp-operator/blob/424a33aa0b82bfe24ea7ba94cbfbe9e46180447d/controllers/validator.go#L110
- https://github.com/openshift/oadp-operator/blob/424a33aa0b82bfe24ea7ba94cbfbe9e46180447d/controllers/validator.go#L113

The goal is to centralize BSL validation in `ValidateBackupStorageLocations` function and centralize VSL validation in `ValidateVolumeSnapshotLocations` function.
