### ISSUE TITLE
Remove deprecated restic old config schema

### ISSUE THREAD

**Issue by mpryc** [openshift/oadp-operator#1176]
This issue is to remove old restic top level config and use nodeagent only. This will also involve removal of restic logs in the tests and other places.

_Originally posted by @mateusoliveira43 in https://github.com/openshift/oadp-operator/pull/1174#discussion_r1347374829_

**Comment by mateusoliveira43** [comment]
not stale

**Comment by mateusoliveira43** [comment]
As discussed, we will only remove fields from our APIs, when those APIs version update

For cases like restic, where the field is not used anymore, we left them present in YAML, but error out if user tries to use them
