### ISSUE TITLE
Add hostname port trimming unit tests to some scenarios (IBM, Noobaa, etc) here https://github.com/openshift/oadp-operator/blob/master/pkg/common/common_test.go to avoid regressions

### ISSUE THREAD

**Issue by kaovilai** [openshift/oadp-operator#1178]
I would add unit tests to some scenarios (IBM, Noobaa, etc) here https://github.com/openshift/oadp-operator/blob/master/pkg/common/common_test.go to avoid regressions

_Originally posted by @mateusoliveira43 in https://github.com/openshift/oadp-operator/pull/1177#discussion_r1352615862_

**Comment by mateusoliveira43** [comment]
Fixed by https://github.com/openshift/oadp-operator/pull/1182, right?

**Comment by kaovilai** [comment]
yup
