### ISSUE TITLE
Add full support for Velero customized install

### ISSUE THREAD

**Issue by dymurray** [openshift/oadp-operator#12]
https://velero.io/docs/v1.4/customize-installation/

- [x] Enable custom plugins
- [x] Install in any namespace
- [x] #175
- [x] Enable Restic integration
- [x] Enable Features (CSI)
- [x] Customize resource requests + limits
- [x] Configure more than one storage location for backup/volumes (minimum 1 per provider ideally N per provider)
- [x] Do not configure BSL during install (optional)
- [x] Use storage provider with self-signed certificate
- [x] #176

0.3.0 Regression
- [x] #379

**Comment by yipng** [comment]
Can the restore-resource-priorities velero server option be included as part of this customization as well?

**Comment by kaovilai** [comment]
0.3.0 release regression from 0.2
Regressed feature
- [ ] Do not configure BSL during install (optional)
