### ISSUE TITLE
Restic backups with PVC backed to NFS remains In Progress

### ISSUE THREAD

**Issue by SergioTeco** [openshift/oadp-operator#120]
I am testing the tool and the backups that include NFS source PVCs remain in "Phase: PartiallyFailed" status. I didn't see problems with other type of volumes, only with NFS and the strange thing is that the 2 times I tested, it advanced a third.
Is there any special configuration for this type?The PVC is 5Gb size.

Restic Backups:
  Completed:
    openshift-metering/hive-metastore-0: datanode-empty, hadoop-config, hadoop-logs, hive-metastore-db-data, namenode-empty
    openshift-metering/hive-server-0: datanode-empty, hadoop-config, hadoop-logs, hive-metastore-auth-tls, hive-metastore-db-data, namenode-empty
    openshift-metering/presto-coordinator-0: hadoop-config, hive-metastore-auth-tls, presto-data, presto-etc, presto-logs, presto-tls
  In Progress:
    openshift-metering/hive-metastore-0: hive-warehouse-data (32.12%)
    openshift-metering/metering-operator-576cb54f4c-tm9x9: runner

**Comment by dymurray** [comment]
https://github.com/openshift/oadp-operator/issues/177

**Comment by dymurray** [comment]
@SergioTeco I am closing this issue as it seems boosting resource allocations for restic fixed your problem.
