### ISSUE TITLE
Add a button to the OADP panel to create a backup from the template of an existing schedule

### ISSUE THREAD

**Issue by poponealex** [openshift/oadp-operator#1203]
**Is your feature request related to a problem? Please describe.**

There is no option on the OADP panel to create a `Backup`  on demand using a `Schedule` instance.

**Describe the solution you'd like**

The option to create a `Backup` from a  `Schedule` template using the OADP panel. 

The velero command for this is: `velero backup create --from-schedule <SCHEDULE_NAME>`

**Comment by shubham-pampattiwar** [comment]
@poponealex OADP does not have a dedicated UI. I believe you are talking about the openshift operatorhub UI ?
if yes, then are you not seeing something like the below screenshot ?
![image](https://github.com/openshift/oadp-operator/assets/17155311/0bfa37c8-e12a-4e1f-96f1-44cb139dbf71)

**Comment by poponealex** [comment]
@shubham-pampattiwar Yes I am talking about the OADP Operator UI.

There is the create instance button for a `Schedule` indeed, this is not my issue though. The feature I am requesting is to have a button to create a backup from an existing schedule as I have explained above.

For instance, when you click on an instance's kebab menu (as show below), it would be a nice feature to be able to create a new backup from this schedule's template. 

![image](https://github.com/openshift/oadp-operator/assets/74072635/a8216505-9057-49a2-bbcd-8c775c8af200)

**Comment by shubham-pampattiwar** [comment]
@poponealex Thanks for explaining. The UI rendered in your screenshot is standard OpenShift OperatorHub UI for CR instances, in our case schedule instances, the options in kebab menu are standard I believe, something the OperatorHub framework provides, not something particular to OADP OperatorHub.

**Comment by kaovilai** [comment]
From [recent exploration](https://github.com/openshift/oadp-operator/pull/1202), you're limited to a few [descriptors](https://github.com/openshift/console/tree/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors#customized-creation-form-with-specdescriptors) to customize the interface without creating a dedicated UI.
[x-descriptors](https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md) can be used to make a field something more usable but nothing like adding a button to create another resource from a resource.

**Comment by poponealex** [comment]
@kaovilai Thank you for the references. I was actually looking into how it would be possible to add actions to a CRD in the Operator schema and I haven't found anything relevant.

It would be a great feature to be able to add some customization to an Operator's UI.

**Comment by kaovilai** [comment]
@poponealex I would create an issue at https://github.com/openshift/console/ if you're still interested in driving this forward.

Maybe around https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md and hope they would route the request to the right people.

At this time this feature is considered unplanned.
