### ISSUE TITLE
VSB and VSR need to be removed from the master branch, they are unnecessary in OADP 1.3+.

### ISSUE THREAD

**Issue by mpryc** [openshift/oadp-operator#1211]
VSB and VSR need to be removed from the master branch. They are unnecessary in OADP 1.3+, but they also don't pose any harm. In the absence of the VSB and VSR in the CRD's / OCP APIs, the description will not be displayed, so adding extra description won't create any issues. For OADP 1.2, this will be a straightforward backport from the master branch because it contains VSB and VSR, which are required in OADP 1.2.

_Originally posted by @mpryc in https://github.com/openshift/oadp-operator/issues/1200#issuecomment-1790860811_

**Comment by mateusoliveira43** [comment]
please close this issue, it is already fixed
