### ISSUE TITLE
Re: proposal to remove pkg/generated from velero, remove the dependency from e2e tests 

### ISSUE THREAD

**Issue by weshayutin** [openshift/oadp-operator#1221]
### Only developers will use GitHub issues for development purposes

agree

**Comment by weshayutin** [comment]
Xun
Propose to delete pkg/generated directory in v1.13:
Issue: https://github.com/vmware-tanzu/velero/issues/6190
Slack: https://kubernetes.slack.com/archives/C021GPR1L3S/p1699276218067089
Decision: we can deprecate it first (keep it updated), and follow the guideline to remove it (We’ll merge 5532, probably n+2) communicate the deprecation via the releasenote or code comment

**Comment by mateusoliveira43** [comment]
unstale

**Comment by mateusoliveira43** [comment]
Velero PR https://github.com/vmware-tanzu/velero/pull/8114 (https://github.com/vmware-tanzu/velero/pull/7627)
