### ISSUE TITLE
Document new branching steps

### ISSUE THREAD

**Issue by mateusoliveira43** [openshift/oadp-operator#1227]
When a new branch (for a new OADP version) is created, some steps must be made. Document these steps.
- [x] #1233

References: 
- https://github.com/openshift/oadp-operator/pull/1226
- https://github.com/openshift/release/pull/45664
- https://github.com/openshift/release/pull/45692
- TODO restic CI PR
- Do not forget to metion vsm/volume-snapshot-mover for branches < 1.3
- add information about this file in CI docs https://github.com/openshift/release/blob/master/core-services/image-mirroring/konveyor/mapping_konveyor_latest
- talk about order and circular dependencies... https://github.com/openshift/release/pull/45811

**Comment by kaovilai** [comment]
> Do not forget to metion vsm/volume-snapshot-mover for branches < 1.3

Don't think we would be branching unless we're making new versions

**Comment by mateusoliveira43** [comment]
Will finish this one first https://github.com/openshift/oadp-operator/pull/1237 before working on this issue

**Comment by mateusoliveira43** [comment]
Talk about build/ci-dockerfile

**Comment by mateusoliveira43** [comment]
add link to flake list https://github.com/openshift/oadp-operator/wiki/FRIGGIN-TIGER-FLAKES

**Comment by mateusoliveira43** [comment]
update this as well https://github.com/openshift/oadp-operator/blob/master/Makefile#L441

**Comment by mateusoliveira43** [comment]
also talk about cron in periodic jobs
