### ISSUE TITLE
Bug: quay.io/konveyor/oadp-operator has not been updated since travis was disabled

### ISSUE THREAD

**Issue by kaovilai** [openshift/oadp-operator#1228]
TODO:
- [ ] Add ci registry promotion to oadp-operator config [like so](https://github.com/openshift/release/blob/99536b99ec49ade8e1e57ac5e8b842852f20a090/ci-operator/config/openshift/velero/openshift-velero-oadp-1.2.yaml#L11-L16)
   - [x] master, done: https://github.com/openshift/release/pull/45344
   - [x] oadp-1.3
   - [ ] oadp-1.2
   - [ ] oadp-1.1
- [ ] Add [mirroring from ci registry to quay](https://github.com/kaovilai/release/blob/master/core-services/image-mirroring/konveyor/mapping_konveyor_latest)
    ```
    registry.ci.openshift.org/konveyor/oadp-operator:latest quay.io/konveyor/oadp-operator:latest
    registry.ci.openshift.org/konveyor/oadp-operator:oadp-1.3 quay.io/konveyor/oadp-operator:oadp-1.3
    registry.ci.openshift.org/konveyor/oadp-operator:oadp-1.2 quay.io/konveyor/oadp-operator:oadp-1.2
    registry.ci.openshift.org/konveyor/oadp-operator:oadp-1.1 quay.io/konveyor/oadp-operator:oadp-1.1
    registry.ci.openshift.org/konveyor/oadp-operator:oadp-1.0 quay.io/konveyor/oadp-operator:oadp-1.0
    ```

[quay.io/konveyor/oadp-operator](https://quay.io/konveyor/oadp-operator)

We did not notice this because devs are not using it during development as we push and use our own images via `make deploy-olm`, and this image is not pulled in any CI either.

Downstream uses image from different build system and is not impacted.

**Comment by mateusoliveira43** [comment]
ci registry promotion PR https://github.com/openshift/release/pull/45344

**Comment by mateusoliveira43** [comment]
PR for mirror will need to add entries here https://github.com/openshift/release/blob/master/core-services/image-mirroring/konveyor/mapping_konveyor_latest

**Comment by kaovilai** [comment]
yup. also need more promotion entries for other branches.

**Comment by mateusoliveira43** [comment]
will wait this one merge https://github.com/openshift/release/pull/45918 before working on this issue
