### ISSUE TITLE
Document how to update OCP versions in CI

### ISSUE THREAD

**Issue by mateusoliveira43** [openshift/oadp-operator#1229]
Document how to update OCP versions in PROW CI

References:
- https://github.com/openshift/release/pull/45344
- promote images from highest OCP version job
- update README links (example: https://github.com/openshift/oadp-operator/pull/1183)

**Comment by mateusoliveira43** [comment]
further discussion topics
- add badge link for periodic unit tests run in README as well
- just have ONE unit test job (can PROW run things unrelated to OCP versions?)

**Comment by kaovilai** [comment]
> just have ONE unit test job (can PROW run things unrelated to OCP versions?)

Probably. Something to ask [testplatform](https://redhat.enterprise.slack.com/archives/CBN38N3MW) or look in repo for more examples.

**Comment by kaovilai** [comment]
> just have ONE unit test job (can PROW run things unrelated to OCP versions?)

Probably. Something to ask [testplatform](https://redhat.enterprise.slack.com/archives/CBN38N3MW) or look in repo for more examples.

**Comment by mateusoliveira43** [comment]
As we have seen, we can use a separate config to have unit tests and images promotion. so, no need to promote highest OCP version job.
