### ISSUE TITLE
Add wiki documentation to docs folder

### ISSUE THREAD

**Issue by mateusoliveira43** [openshift/oadp-operator#1238]
The wiki docs of the repo has interesting documentation (for example https://github.com/openshift/oadp-operator/wiki/Prow-Progress-:-OADP-associated-repositories-from-Openshift-and-Migtools). But it is not referenced in any other parts in `docs/` folder.

Add docs from wiki into `docs/` folder and delete wiki from repo.

**Comment by weshayutin** [comment]
I think we voted this down in scrum.

**Comment by mateusoliveira43** [comment]
at least we need to tell developers/users about it in the docs
