### ISSUE TITLE
Backups with Restic volumes are Partially Failed

### ISSUE THREAD

**Issue by SergioTeco** [openshift/oadp-operator#127]
I am testing the tool and I find failures in backups with volumes of 50G (25g effective usage) or 100G (7G effective usage). In one case the PVB remains in progress or in another case in failure directly.
The PVs are hosted in Vsphere datastore.  
I noticed that the data copy starts in the bucket, but does not complete.

apiVersion: velero.io/v1
kind: Backup
metadata:
  name: quay
  namespace: oadp-operator
  labels:
    velero.io/storage-location: produccion
spec:
  defaultVolumesToRestic: true
  hooks: {}
  includedNamespaces:
    - quay-registry
  snapshotVolumes: true
  storageLocation: produccion
  ttl: 24h0m0s
  volumeSnapshotLocations:
    - produccion

**Comment by dymurray** [comment]
Hey @SergioTeco thanks for the issue. Since restic seems to be the root cause here, it would be useful if you could include the restic pod logs as well as the `podvolumebackup` resource.

**Comment by SergioTeco** [comment]
apiVersion: velero.io/v1
kind: PodVolumeBackup
metadata:
  generateName: quay-
  annotations:
    velero.io/pvc-name: image-registry-storage
  selfLink: /apis/velero.io/v1/namespaces/oadp-operator/podvolumebackups/quay-xvwkh
  resourceVersion: '625812235'
  name: quay-xvwkh
  uid: 0581102c-ef82-46d4-b362-339d740ecaf2
  creationTimestamp: '2021-07-06T18:48:00Z'
  generation: 1
      manager: velero-server
      operation: Update
      time: '2021-07-06T18:48:00Z'
  namespace: oadp-operator
  ownerReferences:
    - apiVersion: velero.io/v1
      controller: true
      kind: Backup
      name: quay
      uid: 6e02f344-51f5-4076-9948-f97a3145f5ea
  labels:
    velero.io/backup-name: quay
    velero.io/backup-uid: 6e02f344-51f5-4076-9948-f97a3145f5ea
    velero.io/pvc-uid: defbb428-9c4a-11ea-ba1c-005056bfcff1
spec:
  backupStorageLocation: produccion
  node: infra01.ocp01.int.cvattv.com.ar
  pod:
    kind: Pod
    name: image-registry-cdbdd7498-bvg7x
    namespace: openshift-image-registry
    uid: 6d9e606d-d9df-4930-aed3-9257f0be9272
  repoIdentifier: 's3:http://10.200.173.250:9000/produccion/restic/openshift-image-registry'
  tags:
    backup: quay
    backup-uid: 2a327d69-2854-4e05-bf47-dae797751537
    ns: openshift-image-registry
    pod: image-registry-cdbdd7498-bvg7x
    pod-uid: 6d9e606d-d9df-4930-aed3-9257f0be9272
    pvc-uid: defbb428-9c4a-11ea-ba1c-005056bfcff1
    volume: registry-storage
  volume: registry-storage
status:
  completionTimestamp: '2021-07-06T18:08:47Z'
  message: 'error running restic backup, stderr=: signal: killed'
  phase: Failed
  progress: {}
  startTimestamp: '2021-07-06T18:08:42Z'

**Comment by SergioTeco** [comment]
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/source-cluster-k8s-gitversion: v1.18.3+45b9524
    velero.io/source-cluster-k8s-major-version: '1'
    velero.io/source-cluster-k8s-minor-version: 18+
  selfLink: /apis/velero.io/v1/namespaces/oadp-operator/backups/quay
  resourceVersion: '625812233'
  name: quay
  uid: 6e02f344-51f5-4076-9948-f97a3145f5ea
  creationTimestamp: '2021-07-06T18:48:00Z'
  generation: 1
      manager: velero-server
      operation: Update
      time: '2021-07-06T18:48:00Z'
  namespace: oadp-operator
  labels:
    velero.io/storage-location: produccion
spec:
  defaultVolumesToRestic: true
  hooks: {}
  includeClusterResources: true
  includedNamespaces:
    - openshift-image-registry
  snapshotVolumes: true
  storageLocation: produccion
  ttl: 24h0m0s
  volumeSnapshotLocations:
    - produccion
status:
  completionTimestamp: '2021-07-06T18:19:10Z'
  errors: 1
  expiration: '2021-07-07T18:08:06Z'
  formatVersion: 1.1.0
  phase: PartiallyFailed
  progress:
    itemsBackedUp: 3066
    totalItems: 3066
  startTimestamp: '2021-07-06T18:08:06Z'
  version: 1

**Comment by SergioTeco** [comment]
apiVersion: velero.io/v1
kind: PodVolumeBackup
metadata:
  generateName: image-registry-backup-
  annotations:
    velero.io/pvc-name: image-registry-storage
  selfLink: >-
    /apis/velero.io/v1/namespaces/oadp-operator/podvolumebackups/image-registry-backup-sj88l
  resourceVersion: '625792004'
  name: image-registry-backup-sj88l
  uid: e02a93f1-a264-4408-8e9a-4278f78ecb26
  creationTimestamp: '2021-07-06T18:29:11Z'
  generation: 2
  managedFields:
    - apiVersion: velero.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:phase': {}
          'f:startTimestamp': {}
      manager: restic-server
      operation: Update
      time: '2021-07-06T18:29:11Z'
    - apiVersion: velero.io/v1
      manager: velero-server
      operation: Update
      time: '2021-07-06T18:29:11Z'
  namespace: oadp-operator
  ownerReferences:
    - apiVersion: velero.io/v1
      controller: true
      kind: Backup
      name: image-registry-backup
      uid: 8752c62d-03bf-456b-bac2-a32ac7a55143
  labels:
    velero.io/backup-name: image-registry-backup
    velero.io/backup-uid: 8752c62d-03bf-456b-bac2-a32ac7a55143
    velero.io/pvc-uid: defbb428-9c4a-11ea-ba1c-005056bfcff1
spec:
  backupStorageLocation: produccion
  node: infra01.ocp01.int.cvattv.com.ar
  pod:
    kind: Pod
    name: image-registry-cdbdd7498-bvg7x
    namespace: openshift-image-registry
    uid: 6d9e606d-d9df-4930-aed3-9257f0be9272
  repoIdentifier: 's3:http://10.200.173.250:9000/produccion/restic/openshift-image-registry'
  tags:
    backup: image-registry-backup
    backup-uid: 8752c62d-03bf-456b-bac2-a32ac7a55143
    ns: openshift-image-registry
    pod: image-registry-cdbdd7498-bvg7x
    pod-uid: 6d9e606d-d9df-4930-aed3-9257f0be9272
    pvc-uid: defbb428-9c4a-11ea-ba1c-005056bfcff1
    volume: registry-storage
  volume: registry-storage
status:
  phase: InProgress
  progress: {}
  startTimestamp: '2021-07-06T18:29:11Z'

**Comment by SergioTeco** [comment]
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/source-cluster-k8s-gitversion: v1.18.3+45b9524
    velero.io/source-cluster-k8s-major-version: '1'
    velero.io/source-cluster-k8s-minor-version: 18+
  selfLink: /apis/velero.io/v1/namespaces/oadp-operator/backups/image-registry-backup
  resourceVersion: '625857299'
  name: image-registry-backup
  uid: 8752c62d-03bf-456b-bac2-a32ac7a55143
  creationTimestamp: '2021-07-06T18:28:39Z'
  generation: 26
      manager: velero-server
      operation: Update
      time: '2021-07-06T19:29:23Z'
  namespace: oadp-operator
  labels:
    velero.io/storage-location: produccion
spec:
  defaultVolumesToRestic: true
  hooks: {}
  includeClusterResources: false
  includedNamespaces:
    - openshift-image-registry
  snapshotVolumes: false
  storageLocation: produccion
  ttl: 24h0m0s
status:
  completionTimestamp: '2021-07-06T19:29:23Z'
  errors: 1
  expiration: '2021-07-07T18:28:39Z'
  formatVersion: 1.1.0
  phase: PartiallyFailed
  progress:
    itemsBackedUp: 115
    totalItems: 115
  startTimestamp: '2021-07-06T18:28:39Z'
  version: 1

**Comment by SergioTeco** [comment]
/velero describe backup image-registry-backup --details
I0707 17:38:47.359567   17219 request.go:645] Throttling request took 1.187467633s, request: GET:https://10.36.0.1:443/apis/healthchecking.openshift.io/v1alpha1?timeout=32s
Name:         image-registry-backup
Namespace:    oadp-operator
Labels:       velero.io/storage-location=produccion
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.18.3+45b9524
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18+

Phase:  PartiallyFailed (run `velero backup logs image-registry-backup` for more information)

Errors:    1
Warnings:  0

Namespaces:
  Included:  openshift-image-registry
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  excluded

Label selector:  <none>

Storage Location:  produccion

Velero-Native Snapshot PVs:  false

TTL:  24h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-07-06 18:28:39 +0000 UTC
Completed:  2021-07-06 19:29:23 +0000 UTC

Expiration:  2021-07-07 18:28:39 +0000 UTC

Total items to be backed up:  115
Items backed up:              115

Resource List:
  apps/v1/ControllerRevision:
    - openshift-image-registry/node-ca-5b8485dd46
    - openshift-image-registry/node-ca-6554ff9f75
    - openshift-image-registry/node-ca-6cc97f9ddf
    - openshift-image-registry/node-ca-6d5f8c6446
    - openshift-image-registry/node-ca-6fff8d6f65
    - openshift-image-registry/node-ca-7dbf69f566
    - openshift-image-registry/node-ca-c8d74d669
    - openshift-image-registry/node-ca-df7f6f9b4
  apps/v1/DaemonSet:
    - openshift-image-registry/node-ca
  apps/v1/Deployment:
    - openshift-image-registry/cluster-image-registry-operator
    - openshift-image-registry/image-registry
  apps/v1/ReplicaSet:
    - openshift-image-registry/cluster-image-registry-operator-57879d7bfc
    - openshift-image-registry/cluster-image-registry-operator-6c64c58d68
    - openshift-image-registry/cluster-image-registry-operator-786dd9b747
    - openshift-image-registry/cluster-image-registry-operator-7975cb6586
    - openshift-image-registry/cluster-image-registry-operator-86d745b478
    - openshift-image-registry/cluster-image-registry-operator-8f94dd955
    - openshift-image-registry/cluster-image-registry-operator-8fcc457c
    - openshift-image-registry/image-registry-57d55b5ccd
    - openshift-image-registry/image-registry-588dd95df4
    - openshift-image-registry/image-registry-68c99b5689
    - openshift-image-registry/image-registry-6d48b7f775
    - openshift-image-registry/image-registry-6f79cc894b
    - openshift-image-registry/image-registry-767bb48c8
    - openshift-image-registry/image-registry-7bc4c7cf4b
    - openshift-image-registry/image-registry-847f5dc7f8
    - openshift-image-registry/image-registry-86ccc9f7cd
    - openshift-image-registry/image-registry-cdbdd7498
    - openshift-image-registry/image-registry-f77f48d6f
  authorization.openshift.io/v1/Role:
    - openshift-image-registry/node-ca
    - openshift-image-registry/prometheus-k8s
  authorization.openshift.io/v1/RoleBinding:
    - openshift-image-registry/node-ca
    - openshift-image-registry/prometheus-k8s
    - openshift-image-registry/system:deployers
    - openshift-image-registry/system:image-builders
    - openshift-image-registry/system:image-pullers
  batch/v1beta1/CronJob:
    - openshift-image-registry/image-pruner
  discovery.k8s.io/v1beta1/EndpointSlice:
    - openshift-image-registry/image-registry-gmn5n
    - openshift-image-registry/image-registry-operator-5xqtb
  monitoring.coreos.com/v1/PrometheusRule:
    - openshift-image-registry/image-registry-operator-alerts
  monitoring.coreos.com/v1/ServiceMonitor:
    - openshift-image-registry/image-registry
    - openshift-image-registry/image-registry-operator
  operators.coreos.com/v1alpha1/ClusterServiceVersion:
    - openshift-image-registry/elasticsearch-operator.4.5.0-202104291943.p0
    - openshift-image-registry/jaeger-operator.v1.17.8
    - openshift-image-registry/kiali-operator.v1.24.7
    - openshift-image-registry/servicemeshoperator.v2.0.5.2
  rbac.authorization.k8s.io/v1/Role:
    - openshift-image-registry/node-ca
    - openshift-image-registry/prometheus-k8s
  rbac.authorization.k8s.io/v1/RoleBinding:
    - openshift-image-registry/node-ca
    - openshift-image-registry/prometheus-k8s
    - openshift-image-registry/system:deployers
    - openshift-image-registry/system:image-builders
    - openshift-image-registry/system:image-pullers
  route.openshift.io/v1/Route:
    - openshift-image-registry/default-route
  v1/ConfigMap:
    - openshift-image-registry/image-registry-certificates
    - openshift-image-registry/serviceca
    - openshift-image-registry/trusted-ca
  v1/Endpoints:
    - openshift-image-registry/image-registry
    - openshift-image-registry/image-registry-operator
  v1/Namespace:
    - openshift-image-registry
  v1/PersistentVolumeClaim:
    - openshift-image-registry/image-registry-storage
  v1/Pod:
    - openshift-image-registry/cluster-image-registry-operator-86d745b478-cr985
    - openshift-image-registry/image-registry-cdbdd7498-bvg7x
    - openshift-image-registry/node-ca-2cfc2
    - openshift-image-registry/node-ca-6w487
    - openshift-image-registry/node-ca-924fv
    - openshift-image-registry/node-ca-g429b
    - openshift-image-registry/node-ca-hbmj2
    - openshift-image-registry/node-ca-hbw2h
    - openshift-image-registry/node-ca-hh8nw
    - openshift-image-registry/node-ca-hzvhb
    - openshift-image-registry/node-ca-kckl7
    - openshift-image-registry/node-ca-khcfb
    - openshift-image-registry/node-ca-lxgzh
    - openshift-image-registry/node-ca-nqx9d
    - openshift-image-registry/node-ca-p7drf
    - openshift-image-registry/node-ca-q7ggz
    - openshift-image-registry/node-ca-vqzz4
    - openshift-image-registry/node-ca-vsmvv
    - openshift-image-registry/node-ca-wdff4
    - openshift-image-registry/node-ca-z2k4x
  v1/Secret:
    - openshift-image-registry/builder-dockercfg-rk2qr
    - openshift-image-registry/builder-token-dtbq9
    - openshift-image-registry/builder-token-v9jcx
    - openshift-image-registry/cluster-image-registry-operator-dockercfg-d9sv5
    - openshift-image-registry/cluster-image-registry-operator-token-6cvl8
    - openshift-image-registry/cluster-image-registry-operator-token-8z6kp
    - openshift-image-registry/default-dockercfg-2fmwm
    - openshift-image-registry/default-token-bjz6v
    - openshift-image-registry/default-token-kfsgc
    - openshift-image-registry/deployer-dockercfg-zcpx2
    - openshift-image-registry/deployer-token-pjt2k
    - openshift-image-registry/deployer-token-pvj6p
    - openshift-image-registry/image-registry-operator-tls
    - openshift-image-registry/image-registry-private-configuration
    - openshift-image-registry/image-registry-tls
    - openshift-image-registry/installation-pull-secrets
    - openshift-image-registry/node-ca-dockercfg-px5t5
    - openshift-image-registry/node-ca-token-dznhd
    - openshift-image-registry/node-ca-token-m2t7g
    - openshift-image-registry/pruner-dockercfg-xsp9p
    - openshift-image-registry/pruner-token-7gvfq
    - openshift-image-registry/pruner-token-n2psm
    - openshift-image-registry/registry-dockercfg-kzdds
    - openshift-image-registry/registry-token-c7vp8
    - openshift-image-registry/registry-token-fpjfh
  v1/Service:
    - openshift-image-registry/image-registry
    - openshift-image-registry/image-registry-operator
  v1/ServiceAccount:
    - openshift-image-registry/builder
    - openshift-image-registry/cluster-image-registry-operator
    - openshift-image-registry/default
    - openshift-image-registry/deployer
    - openshift-image-registry/node-ca
    - openshift-image-registry/pruner
    - openshift-image-registry/registry

Velero-Native Snapshots: <none included>

Restic Backups:
  Completed:
    openshift-image-registry/image-registry-cdbdd7498-bvg7x: registry-tls
  In Progress:
    openshift-image-registry/image-registry-cdbdd7498-bvg7x: registry-storage

**Comment by SergioTeco** [comment]
/velero describe backup quay          
I0707 17:41:36.048361   17317 request.go:645] Throttling request took 1.189497708s, request: GET:https://10.36.0.1:443/apis/apiextensions.k8s.io/v1beta1?timeout=32s
Name:         quay
Namespace:    oadp-operator
Labels:       velero.io/storage-location=produccion
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.18.3+45b9524
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18+

Phase:  PartiallyFailed (run `velero backup logs quay` for more information)

Errors:    1
Warnings:  0

Namespaces:
  Included:  openshift-image-registry
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  included

Label selector:  <none>

Storage Location:  produccion

Velero-Native Snapshot PVs:  true

TTL:  24h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-07-06 18:08:06 +0000 UTC
Completed:  2021-07-06 18:19:10 +0000 UTC

Expiration:  2021-07-07 18:08:06 +0000 UTC

Total items to be backed up:  3066
Items backed up:              3066

Velero-Native Snapshots: <none included>

Restic Backups (specify --details for more information):
  Completed:  1
  Failed:     1

**Comment by SergioTeco** [comment]
Hi Dylan. I have attached the PVB and Backup objects from the NS openshift-image-registry backup and logs. It remains to add the Restic pod log of the node where the pod lives.

**Comment by SergioTeco** [comment]
We have changed the resources for Restic in Velero

restic_resource_allocation:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi

and then the issue is gone. The only issue that seems to remain is for NFS volumes. I create a ticket for that, https://github.com/openshift/oadp-operator/issues/120
