### ISSUE TITLE
Bug: OADP 1.3.0 restore shows "The secret is not getting created" on openshift 4.15 cluster.

### ISSUE THREAD

**Issue by Frank51** [openshift/oadp-operator#1542]
### Description:
When using OADP 1.3.0 to run restore a namespace on openshift 4.15 cluster, the metadata inside the namespace restore works. But even though there is no secret yaml inside the namespace, the velero log shows "The secret is not getting created". But OADP 1.3.0 works on openshift 4.14 cluster.

### Velero log part:
https://gist.github.com/Frank51/0bfbe166fec2eff8be2e94cc423c0cbb

### Workaround:
After upgrading OADP from 1.3.0 to 1.3.3. The restore works then. And this error message no longer shows up.

**Comment by kaovilai** [comment]
My guess is https://github.com/openshift/openshift-velero-plugin/pull/228 fixes it.

**Comment by kaovilai** [comment]
cherrypick to OADP 1.3 in https://github.com/openshift/openshift-velero-plugin/pull/235 which goes into 1.3.1
as part of https://issues.redhat.com/browse/OADP-3598
