### ISSUE TITLE
Add legacy-aws to e2e

### ISSUE THREAD

**Issue by kaovilai** [openshift/oadp-operator#1566]
TODO: Add legacy-aws to e2e

_Originally posted by @kaovilai in https://github.com/openshift/oadp-operator/issues/1565#issuecomment-2430193048_

https://redhat-internal.slack.com/archives/C039LRSDC8Z/p1729628722036969 suggests using legacy-aws defaultplugin and do a fsbackup which should check for node-agent readiness.

**Comment by weshayutin** [comment]
should not be required.. as it's dupe to any oadp-1.3 job.  QE will take responsibility.

**Comment by kaovilai** [comment]
requirements moved to https://issues.redhat.com/browse/OADP-5106
