### ISSUE TITLE
Document restic nuances with NFS volumes and `root_squash`

### ISSUE THREAD

**Issue by dymurray** [openshift/oadp-operator#179]
With root_squash, restic will be mapped to `nfsnobody` and will not have enough permissions to perform the backup/restore. This has been documented in our MTC product as well as customers also required the use of root_squash and ran into some issues (see here: https://docs.openshift.com/container-platform/4.7/migration-toolkit-for-containers/troubleshooting-mtc.html#restic-permission-error-when-migrating-from-nfs-storage-with-root-squash-enabled_troubleshooting-mtc).

There are 2 ways to get around this issue:
1. Use supplemental groups and apply this same supplemental group to the restic daemonset (this change will need to be submitted to OADP as well to mimic MTC, which shouldn't be an issue if this is strongly desired)
2. Set no_root_squash

**Comment by henrychi2** [comment]
Even with supplemental groups, the restic pod still won't be able to copy files that don't have group permissions correct?  From the example in #133, there is a file like
```
-rw-------. 1 1000610000 nobody  33 Jul 13 14:23 .erlang.cookie
```

The file .erlang.cookie doesn't have group permissions.  Doesn't that mean only the owner or root can copy the file?

**Comment by sseago** [comment]
And with root squashing, that would require that restic run *as the owner*. I'm not sure how that would work here, though.

**Comment by henrychi2** [comment]
The files to backup have different owners too.  Unless I'm missing something, it seems like Velero with restic just doesn't work with root squash enabled.

**Comment by sseago** [comment]
I imagine rsync-based solutions would have the same problem, actually. @dymurray -- is there any way around this issue?

**Comment by shawn-hurley** [comment]
@eemcmullan Seems like this issue can be closed?
