### ISSUE TITLE
OADP Lab

### ISSUE THREAD

**Issue by dymurray** [openshift/oadp-operator#272]
We need to produce a training lab for CEE to be able to learn about OADP. To do this, we need to setup a workload in agnosticd to enable an OADP lab environment similar to https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles_ocp_workloads/ocp4_workload_migration_training.

Related: https://github.com/openshift/oadp-operator/issues/324

**Comment by dymurray** [comment]
https://github.com/konveyor/labs/tree/master/mtc

**Comment by kaovilai** [comment]
Dependent on
- [ ] https://github.com/openshift/oadp-operator/issues/324
