### ISSUE TITLE
Implement Telemetry metrics for OADP operator

### ISSUE THREAD

**Issue by dymurray** [openshift/oadp-operator#308]
This task requires understanding what our operator needs to expose in order to be integrated into OCP's telemetry system. For reference, see mig-controller's implementation.

**Comment by kaovilai** [comment]
@shubham-pampattiwar can this close?

**Comment by shubham-pampattiwar** [comment]
Related PRs:
https://github.com/openshift/oadp-operator/pull/410
https://github.com/openshift/oadp-operator/pull/537
https://github.com/openshift/oadp-operator/pull/579
https://github.com/openshift/cluster-monitoring-operator/pull/1536
