### ISSUE TITLE
E2E tests should be updated to test backup/restore of volumes with restic

### ISSUE THREAD

**Issue by dymurray** [openshift/oadp-operator#339]
Backup/restore test suite should be running a backup/restore of a stateful app using:
1. CSI
2. Restic
3. Cloud-snapshots

The E2E tests should also be running some type of verification that the data is properly restored and usable.

**Comment by dymurray** [comment]
CSI and snapshots are done, just need restic now.

**Comment by kaovilai** [comment]
As of #531 restic is implemented in e2e
