### ISSUE TITLE
init container setup-certificate-secret crashes with error cp: cannot create regular file '/certs/ca-bundle.crt': Permission denied

### ISSUE THREAD

**Issue by gorantornqvist** [openshift/oadp-operator#346]
**Describe the bug**

After node restarts I found that the velero init container setup-certificate-secret crashes with error:
```
cp: cannot create regular file '/certs/ca-bundle.crt': Permission denied
cp: cannot create regular file '/certs/ca-bundle.trust.crt': Permission denied
```
After a manual restart of the pod, it starts working again.
Or if you wait for a while it starts working again as well.
So low impact / severity I would say.

**To Reproduce**
1. In this environment  'Openshift 4.8.12'
2. With this config:
```
apiVersion: konveyor.openshift.io/v1alpha1
kind: Velero
metadata:
  creationTimestamp: '2021-09-20T07:10:03Z'
  generation: 1
      manager: kubectl-create
      operation: Update
      time: '2021-09-20T07:10:03Z'
  name: demo-customer
  namespace: oadp-operator
  resourceVersion: '132174569'
  uid: fa4a304a-a763-4803-a3a2-29ea384c818a
spec:
  backup_storage_locations:
    - config:
        insecureSkipTlsVerify: 'false'
        profile: default
        region: us-east-1
        s_3__force_path_style: 'true'
        s_3__url: 'https://our-netapp-storagegrid'
        signatureVersion: '4'
      credentials_secret_ref:
        name: cloud-credentials
        namespace: oadp-operator
      name: nimbus-demo-customer
      object_storage:
        bucket: nimbus-demo-customer-ec-u12-dr01
        caCert: >-
          LS0tLS1CRUdJTiBDR........S0tLQo=
        prefix: nimbus
      provider: aws
  default_velero_plugins:
    - aws
    - csi
    - openshift
  enable_restic: true
  olm_managed: true
  velero_feature_flags: EnableCSI
status:
  conditions:
    - ansibleResult:
        changed: 0
        completion: '2021-09-28T10:20:23.42279'
        failures: 0
        ok: 17
        skipped: 47
      lastTransitionTime: '2021-09-28T09:28:46Z'
      message: Awaiting next reconciliation
      reason: Successful
      status: 'True'
      type: Running

# cacert is a cabundle for our internal ca, intermediate and root ca cert.
```
3. Reboot the node / or maybe restart pod(s) in a particular order, not sure on specifics.

**Expected behavior**

The velero pod should start right away.

I found that the operator pod logs contains some sensitive information. Let me know if you need it and I can try to remove that info. The velero pod has been restarted so no usable logs there, I can gather those next time it happens.

**Version of operator being used**
 - OADP operator 0.2.6 from operatorhub

**Comment by dymurray** [comment]
@gorantornqvist We recently released 0.3.0 which changes how the custom CA certs are populated and consumed by Velero. Would you be willing to retest this setup on 0.3.0 and see if the problem still exists? For information on upgrading, see: https://github.com/openshift/oadp-operator/blob/master/docs/upgrade.md

**Comment by gorantornqvist** [comment]
Hi,
Sure, I will upgrade to 0.3.0 and see if it is the same ...

**Comment by gorantornqvist** [comment]
I believe we can close this, I havent seen the same behaviour on 0.3.0, thanks ...
