### ISSUE TITLE
Bug: stateful example fails using Openshift Data Foundation

### ISSUE THREAD

**Issue by chechuironman** [openshift/oadp-operator#376]
### Contact Details

chechuironman@gmail.com

### Describe bug

I was following the example for stateful app, but I got this error on the restore

Generated from openshift-storage.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-545d8c7b69-zhlk4_c44302e1-5271-4b89-ba62-36c6a227ead7
12 times in the last 34 minutes
failed to provision volume with StorageClass "ocs-storagecluster-cephfs": rpc error: code = Internal desc = key not found: no snap source in omap for "csi.snap.641afee4-2752-11ec-9386-96fed163b320"

I'm using OCP 4.7 and ODF 4.7

how can I restore the PVs in other cluster as Im trying? (both clusters are identical)

### What happened?

A bug happened!

### OADP Version

0.3.x (Beta)

### OpenShift Version

4.7

### New issue

- [X] This issue is new

**Comment by dymurray** [comment]
@chechuironman this error can happen if your `volumesnapshotclass` `reclaimPolicy` is not set to `Retain`. Can you please paste the contents of:
```
$ oc get volumesnapshotclasses -o yaml
```
