### ISSUE TITLE
Add debugging steps for failed B/R to TROUBLESHOOTING.md

### ISSUE THREAD

**Issue by eemcmullan** [openshift/oadp-operator#377]
As of now, there is an outline provided in https://github.com/openshift/oadp-operator/blob/master/TROUBLESHOOTING.md that details what troubleshooting topics need to be expanded upon, which need to be filled.

**Comment by kaovilai** [comment]
We now have docs at https://github.com/openshift/oadp-operator/blob/master/docs/TROUBLESHOOTING.md covering topics in this issue.
