### ISSUE TITLE
Add Ability To Setup S3 and GCS Buckets

### ISSUE THREAD

**Issue by dustman9000** [openshift/oadp-operator#390]
**Overview**
As part of the [Managed Velero Operator](https://github.com/openshift/managed-velero-operator) (MVO) for OpenShift Dedicated (OSD), the S3/GCS buckets are created prior to setting up velero for use. This allows for zero-touch install for OSD customers and provides consistency across the fleet of OSD clusters.

**Description**
In order to be a full replacement of the managed-velero-operator for OSD, setup the S3 or GCS buckets prior to setting up and using velero. 

**Alternatives**
An alternative approach, would to create an additional operator that acts as a wrapper around the OADP operator. This would add additional unneeded complexity to wrap around an operator that already acts as a wrapper around velero.

**Additional context**
- MVO [reconcile call to CreateStorage()](https://github.com/openshift/managed-velero-operator/blob/6142ca3ae690718656afcb038de650343752959f/pkg/controller/velero/controller.go#L151)
- MVO S3 [CreateStorage()](https://github.com/openshift/managed-velero-operator/blob/6142ca3ae690718656afcb038de650343752959f/pkg/storage/s3/s3.go#L53)
- MVO GCS [CreateStorage()](https://github.com/openshift/managed-velero-operator/blob/6142ca3ae690718656afcb038de650343752959f/pkg/storage/gcs/gcs.go#L53)
- MVO [credential request](https://github.com/openshift/managed-velero-operator/blob/d9bc6780f8ae8b13245c5de22a301f5054da8217/hack/olm-registry/olm-artifacts-template.yaml#L91-L133)

**Comment by kaovilai** [comment]
Any inputs on how you want deletion to work?

**Comment by dustman9000** [comment]
Ideally we would like the bucket to be deleted upon deletion of the CR.

**Comment by kaovilai** [comment]
As of latest work.. you can add a label to confirm you want to delete the bucket then the CR finalizer will be removed.
If you don't add a label to confirm, finalizer will prevent CR from deleting.
You can choose to remove finalizer yourself to skip deletion of bucket at cloud provider and clear CR from cluster.

**Comment by kaovilai** [comment]
But the enhancement work is paused per jira
