### ISSUE TITLE
Change OADP operator to be namespace-scoped instead of cluster-scoped

### ISSUE THREAD

**Issue by dymurray** [openshift/oadp-operator#419]
There is no need for OADP operator to be a cluster-scoped operator. This prevents us from fully supporting use cases needed for MTC integration as well as other team's use cases. We should change our operator to only watch the current namespace for CRs.

**Comment by kaovilai** [comment]
@dymurray FYI this will break if/when we have to accommodate [OLMv1](https://operator-framework.github.io/operator-controller/project/olmv1_design_decisions/)

> TL;DR: OLM v1 cannot feasibly support multi-tenancy or any feature that assumes multi-tenancy.
