### ISSUE TITLE
Bug: Velero restore fails to pull image from internal OpenShift registry.

### ISSUE THREAD

**Issue by Bloom-P** [openshift/oadp-operator#425]
### Contact Details

sparpate@redhat.com

### Describe bug

When velero restores the backed up files to a new namespace due to which the imagestream throws an error as it tries to pull application images from external nexus registry instead of pulling them from the internal OpenShift registry.
~~~
 velero backup create <name of backup> --include-namespace <namespace>
 velero restore create <name of restore> --from-backup <name of backup>
~~~

The resources are successfully created. However when we try restoring we face ImagePullbackOff error.

In events, we noticed that it is trying to pull from nexus registry instead of internal OCP registry:
~~~
2m10s       Warning   Failed                   pod/locator-1-m8n5c                  Error: ImagePullBackOff
2m24s       Normal    Pulling                  pod/locator-1-m8n5c                  Pulling image "nexus.xxx:5000/locator@sha256:726f4551df12d6bc7b30155e09096bbea65de48c4ad9ccceb6d3e2ff9bcf9a27"
2m24s       Warning   Failed                   pod/locator-1-m8n5c                  Failed to pull image "nexus.xxx:5000/locator@sha256:726f4551df12d6bc7b30155e09096bbea65de48c4ad9ccceb6d3e2ff9bcf9a27": rpc error: code = Unknown desc = error pinging docker registry nexus.xxx:5000: Get "https://nexus.xxx:5000/v2/": http: server gave HTTP response to HTTPS client
2m24s       Warning   Failed                   pod/locator-1-m8n5c                  Error: ErrImagePull
2m36s       Normal    BackOff                  pod/locator-1-m8n5c                  Back-off pulling image "nexus.xxx:5000/locator@sha256:726f4551df12d6bc7b30155e09096bbea65de48c4ad9ccceb6d3e2ff9bcf9a27"
~~~

We noticed that there are two plugins in velero yaml.
~~~
defaultVeleroPlugins:
  - aws
  - openshift
~~~

Steps to reproduce:

1. Build the image and push it to nexus docker registry:
docker build -f ./Dockerfile -t nexusregistry:5000/sample-app .
docker push nexusregistry:5000/sample-app 

2. Login to the OCP Cluster and the internal registry:
$ oc login --insecure-skip-tls-verify -u '${OCP_CREDS_USR}' -p '${OCP_CREDS_PSW}' ${ocpUrl}
$ sudo docker login -u system -p \$(oc whoami -t) ${ocpRegistry}

3. There is a script which is executed at customer's end which has docker tag and push to the internal registry commands. Due to which pipeline job runs and resources(pods,deployment,is, etc) are created.

### What happened?

We expect the images to be pulled from the internal OpenShift registry rather than the external registry.

### OADP Version

0.4.x (Beta)

### OpenShift Version

4.6

### New issue

- [X] This issue is new

**Comment by Bloom-P** [comment]
I'll attach the backup/restore logs along with `oc get imagestream locator -oyaml` shortly.

**Comment by Bloom-P** [comment]
[islocatore.txt](https://github.com/openshift/oadp-operator/files/7474947/islocatore.txt) --> Imagestream yaml of the image
[backuplogs.txt](https://github.com/openshift/oadp-operator/files/7474951/backuplogs.txt) --> Velero Backup logs
[restorelogs.txt](https://github.com/openshift/oadp-operator/files/7474952/restorelogs.txt) --> Velero Restore logs
[errors.txt](https://github.com/openshift/oadp-operator/files/7474955/errors.txt) --> Velero backup error logs

**Comment by dymurray** [comment]
@Bloom-P Here's what I am seeing... the Imagestream has this:
```
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: nexus.abc.com:5000/locator:4.2.0-31-project
    generation: 22
    importPolicy:
      insecure: true
    name: 4.2.0-31-project
    referencePolicy:
      type: Source
```

If you have this in the Imagestream spec, then this is exactly how we will restore the imagestream onto the cluster. This DockerImage must be accessible from the cluster or this will fail. I'm failing to see how this is unexpected behavior.

If that host is unreachable, I don't think you want this imagestream definition. What am I missing?

**Comment by sseago** [comment]
It's not clear from the comments, but what resource are the ImagePullbackOff errors coming from? I'm assuming it's from a pod of some sort. Could you provide the pod (and associated Deployment/DC/etc.) yaml for this resource for the post-restore failure and also for the yaml before backup (if available)?

**Comment by Bloom-P** [comment]
@dymurray They are storing their images in nexus and tagging them to the internal registry.

Adding a scrennshot of the stage in Jenkins.
![push](https://user-images.githubusercontent.com/87317320/142254448-e3d23d33-a705-4493-982f-f381fca0059a.PNG)

@sseago I'll attach the requested outputs as I receive them.
