### ISSUE TITLE
Enable cluster-wide proxy support

### ISSUE THREAD

**Issue by dymurray** [openshift/oadp-operator#440]
We need to update OADP operator and all of its dependencies to consume the cluster-wide proxy configuration values and respect them.

This is done in MTC already, so most of our dependencies already have support, it's just a matter of properly passing these env vars through the operator.

**Comment by kaovilai** [comment]
IIUC
User would configure cluster-wide proxy first via https://docs.openshift.com/container-platform/4.9/networking/enable-cluster-wide-proxy.html#enable-cluster-wide-proxy
> Operator Lifecycle Manager (OLM) automatically configures Operators that it manages with the cluster-wide proxy

Enabling proxy support for operator doc
https://docs.openshift.com/container-platform/4.9/operators/operator_sdk/golang/osdk-golang-tutorial.html#osdk-run-proxy_osdk-golang-tutorial

**Comment by kaovilai** [comment]
> To support proxied clusters, your Operator must inspect the environment for the following standard proxy variables and pass the values to Operands:
> - HTTP_PROXY
> - HTTPS_PROXY
> - NO_PROXY
