### ISSUE TITLE
Bug: kube-rbac-proxy is not pulled from quay.io

### ISSUE THREAD

**Issue by thomasGusenleitner** [openshift/oadp-operator#500]
### Contact Details

thomas.gusenleitner@voestalpine.com

### Describe bug

Hi,

The  kube-rbac-proxy is pulled from grc.io/kubebuilder/. In our semi restricted environment "grc.io/kubebuilder/" is not enabled at the moment. This breaks the update to operator version 0.5.1.

Is it possible to use a kube-rbac-proxy hosted on quay.io instead. for example https://quay.io/repository/redhat-cop/kube-rbac-proxy ?

Best  Regards,
Thomas

### What happened?

Upgrade to 0.5.1 not possible

Failed to pull image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0": rpc error: code = Unknown desc = Source image rejected: Running image docker://gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0 is rejected by policy.

### OADP Version

0.5.x (Stable)

### OpenShift Version

4.8

### New issue

- [X] This issue is new

**Comment by shawn-hurley** [comment]
I believe that this will be fixed in the next release of OADP as we actually don't need `kube-rbac-proxy`, it was added erroneously. 

removing it here: https://github.com/openshift/oadp-operator/pull/504
