### ISSUE TITLE
OADP installation fails in disconnected OCP environment

### ISSUE THREAD

**Issue by netzzer** [openshift/oadp-operator#53]
If OADP is installed in a disconnected environment the result is the oadp-operator will fail as well as the velero service even after quay.io/konveyor is added to the OCP imagecontentsourcepolicy so that images can be pulled from this location.

```
# oc get pods
NAME                                        READY   STATUS                  RESTARTS   AGE
oadp-default-aws-registry-7f4ccc484-4qm48   0/1     ImagePullBackOff        0          43h
oadp-operator-86dc5c8578-zgmxf              0/1     ImagePullBackOff        0          4m58s
velero-598fb6447-z5vqd                      0/1     Init:ImagePullBackOff   0          42h
velero-5cf5445d97-wk45p                     0/1     Init:ImagePullBackOff   0          43h
```
For disconnected deployments the following should be done:

1) All image pulls must use image@sha

2) All image@sha needed for any of the CRs should be listed in CSV relatedImages. This is needed for disconnected air gap environments where the mirror registry has to be pre-populated with all image@sha that will be needed for a particular OADP version. Once the registry is disconnected OADP can be installed using these images.

3) Image pulls should be from a single location (i.e. quay.io/konveyer; registry.redhat.io) if possible and docker.io should not be used because most customers in disconnected OCP envs will not whitelist docker.io due to security concerns.

**Comment by dymurray** [comment]
This will also require that we fork the CSI plugin and carry it under Konveyor as well.

This work has been put on hold temporarily.

**Comment by dymurray** [comment]
https://github.com/konveyor/velero-plugin-for-csi/commit/02bcab7225d5dc6848261c28cd1c800ebe483e83

CSI fork with UBI dockerfile

**Comment by dymurray** [comment]
RE: images and their shas... we need to go through all the image vars and ensure there is a field `****_fqin` much like mig-operator that would allow someone to override the entire image substitution.

We also need to enable this in the CSV

**Comment by shubham-pampattiwar** [comment]
fixed by https://github.com/openshift/oadp-operator/pull/448
