### ISSUE TITLE
Bug: Restore namespace metadata failed via OADP Velero 0.2.3

### ISSUE THREAD

**Issue by Frank51** [openshift/oadp-operator#538]
### Contact Details

yunqian.chen@dell.com

### Describe bug

Restoring metadata via oadp Velero failed. And the oadp version is 0.2.3. After restoration failed, it shows such error message.

`"Unable to restore namespace 'ace-apps-test' using Velero.  {\"namespaces\":{\"ace-apps-test-restore\":[\"error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/apps-cp4i-ad-stcpay-com-sa: admission webhook \\\"mutate.configuration.upsert.appconnect.ibm.com\\\" denied the request: version is not supported\",\"error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/bulkblock-is-is-adminssl: admission webhook \\\"mutate.configuration.upsert.appconnect.ibm.com\\\" denied the request: version is not supported\",\"error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/callback-is-is-adminssl: admission webhook \\\"mutate.configuration.upsert.appconnect.ibm.com\\\" denied the request: version is not supported\",\"error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/cp4i-ad-stcpay.jks: admission webhook \\\"mutate.configuration.upsert.appconnect.ibm.com\\\" denied the request: version is not supported\",\"error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/demo-is-adminssl: admission webhook \\\"mutate.configuration.upsert.appconnect.ibm.com\\\" denied the request: version is not supported\",\"error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/ibmspsandbox-ad-stcpay-com-sa: admission webhook \\\"mutate.configuration.upsert.appconnect.ibm.com\\\" denied the request: version is not supported\",\"error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/integration1-stcpay-com-sa: admission webhook \\\"mutate.configuration.upsert.appconnect.ibm.com\\\" denied the request: version is not supported\",\"error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/server-conf: admission webhook \\\"mutate.configuration.upsert.appconnect.ibm.com\\\" denied the request: version is not supported\",\"error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/setdbparms-conf: admission webhook \\\"mutate.configuration.upsert.appconnect.ibm.com\\\" denied the request: version is not supported\"]}}.  Unable to restore '08ec76ff-7443-53d8-8391-8690bde5675d-2021-12-13-12-58-06-ace-apps-test-restore' using Velero: ."`

### What happened?

Restoring metadata in namespace via Velero failed. Based on the log, it complains "denied the request: version is not supported". 

### OADP Version

0.2.x (Alpha)

### OpenShift Version

4.6

### Velero pod logs

```shell
https://gist.github.com/Frank51/0fb870d191839b8a429dee737049d897
```

### New issue

- [X] This issue is new

**Comment by kaovilai** [comment]
I would look at if you have any of `kind: MutatingWebhookConfiguration` in the cluster
https://docs.openshift.com/container-platform/4.9/architecture/admission-plug-ins.html#mutating-admission-plug-in_admission-plug-ins
```sh
> oc get MutatingWebhookConfiguration
```
Within these objects yaml, look at the rules enforced if it is blocking creation of the objects experiencing issues in the log above.
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#rulewithoperations-v1-admissionregistration-k8s-io

**Comment by kaovilai** [comment]
reformatting error
```json
{
    "namespaces": {
        "ace-apps-test-restore": [
            "error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/apps-cp4i-ad-stcpay-com-sa: admission webhook \"mutate.configuration.upsert.appconnect.ibm.com\" denied the request: version is not supported",
            "error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/bulkblock-is-is-adminssl: admission webhook \"mutate.configuration.upsert.appconnect.ibm.com\" denied the request: version is not supported",
            "error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/callback-is-is-adminssl: admission webhook \"mutate.configuration.upsert.appconnect.ibm.com\" denied the request: version is not supported",
            "error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/cp4i-ad-stcpay.jks: admission webhook \"mutate.configuration.upsert.appconnect.ibm.com\" denied the request: version is not supported",
            "error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/demo-is-adminssl: admission webhook \"mutate.configuration.upsert.appconnect.ibm.com\" denied the request: version is not supported",
            "error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/ibmspsandbox-ad-stcpay-com-sa: admission webhook \"mutate.configuration.upsert.appconnect.ibm.com\" denied the request: version is not supported",
            "error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/integration1-stcpay-com-sa: admission webhook \"mutate.configuration.upsert.appconnect.ibm.com\" denied the request: version is not supported",
            "error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/server-conf: admission webhook \"mutate.configuration.upsert.appconnect.ibm.com\" denied the request: version is not supported",
            "error restoring configurations.appconnect.ibm.com/ace-apps-test-restore/setdbparms-conf: admission webhook \"mutate.configuration.upsert.appconnect.ibm.com\" denied the request: version is not supported"
        ]
    }
}
```

**Comment by kaovilai** [comment]
This is the relevant mutatingwebhookconfiguration rules found from gathered info
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ibm-appconnect-mutating-webhook-openshift-operators
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: <redacted>
    service:
      name: ibm-appconnect-webhook-openshift-operators
      namespace: openshift-operators
      path: /admissionwebhook/mutatesecretconfigurationupsert
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mutate.configuration.upsert.appconnect.ibm.com
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - appconnect.ibm.com
    apiVersions:
    - v1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - configurations
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
...
```

**Comment by kaovilai** [comment]
IIUC: `configurations.appconnect.ibm.com` type appears to be a managed resource that is discouraged from manual mutation (create/update/delete) per
https://www.ibm.com/docs/en/app-connect/containers_cd?topic=troubleshooting-effect-reconciliation-loop-customized-settings-managed-resources

Likely these objects failing restore are objects with ownerReferences. It should be sufficient to restore the owners alone and let the  IBM® App Connect Operator create these objects for you.

**Comment by kaovilai** [comment]
This docs might be of interest. It shows supported operator version/channel which maybe related to why it is being blocked from restore.
https://www.ibm.com/docs/en/app-connect/containers_cd?topic=resources-specversion-values

**Comment by kaovilai** [comment]
If anyone want to follow along: try installing this IBM operator instruction https://www.ibm.com/docs/en/app-connect/containers_cd?topic=operator-installing-red-hat-openshift
Then try to create configurations

**Comment by kaovilai** [comment]
Upon further investigation in the [CRD](https://gist.github.com/kaovilai/6b536dd642a98540f6734e69e398e8ae#file-configurations-appconnect-ibm-com-crd-yaml-L173-L177) and testing various values I was able to repliciate admission webhook error seen here
![image](https://user-images.githubusercontent.com/11228024/150886453-d834ac58-cd6e-40b6-ae59-69e211fa4bb5.png)

IIUC: The version string used (in this case `"2.1"`) is not found in [supported version matrix](https://www.ibm.com/docs/en/app-connect/containers_cd?topic=resources-specversion-values) ie. supported values today would be "12.0.2.0-r2" and so on.

So double check if the versions used at backup time is still considered supported by the installed operator.

**Comment by kaovilai** [comment]
filed an issue that may help this situation in the future https://github.com/vmware-tanzu/velero/issues/4572
