### ISSUE TITLE
After deleting Velero backup registry image data exists in the BSL

### ISSUE THREAD

**Issue by dymurray** [openshift/oadp-operator#55]
Because we are putting the registry images inside of a separate folder in the S3 bucket (`docker/registry`) the `velero delete backup` command will leave the registry image backup data in the s3 bucket and will not be automatically cleaned up.

We need to explore whether this problem can be resolved by either:

- Putting the registry images under the `velero` directory in the BSL (specifically under the current backup)
- Attaching some type of owner reference that the `velero delete backup` command respects

Unsure on the best way to solve and will likely require some changes upstream with the `BackupDeletionRequest` code.

**Comment by sseago** [comment]
Keep in mind that we're deliberately not associating this image data with a specific backup since the same registry lives across stage migrations (and thus across multiple backups) for a given migplan. We need to tie mig registry data deletion to the closing of migplans rather than the deletion of velero backups.

**Comment by GMerigo** [comment]
@sseago does this apply also to restic backups? It seems that restic data does not get deleted too.

**Comment by sseago** [comment]
I'm not sure about restic backups, although that's completely different than this. The registry data referenced here is completely outside of Velero. The restic backups are managed by velero. Whether or not they're deleted with the velero backup is definitely an upstream concern as well as ours. If we're sure that deleting velero backups deletes velero backup data but not restic snapshots, then we should probably open an upstream issue there.

**Comment by sousaaguilherme** [comment]
Is there a fix for this issue yet, or a safe workaround for cleaning old, unreferenced images?

Our registry backup is getting very large.

**Comment by kaovilai** [comment]
> a safe workaround for cleaning old, unreferenced images?

You could use the registry dir in the storage and stand up a private registry pointing to it, then follow https://stackoverflow.com/a/43786939/4590470 to delete each tags you don't need and then run garbage collection.

**Comment by kaovilai** [comment]
You can also delete docker dir in storage and then run a new backup to just keep the latest tags.

**Comment by sousaaguilherme** [comment]
@kaovilai  thanks for the feedback. Are there any plans on implementing this type of purge into oadp? this might solve things for a while, but it's temporary...

**Comment by kaovilai** [comment]
It might requires updating the underlying docker registry code. It's not going to be simple unfortunately. The best thing to do is to store your images in a highly available registry off cluster imo then you won't be triggering this internal imagestream backup functionality.
