### ISSUE TITLE
Velero Backup Storage Locations, Provider Parameter

### ISSUE THREAD

**Issue by gammohamed** [openshift/oadp-operator#552]
Hello,
For the Velero Backup Storage Locations, Provider Parameter
Can  it be locally stored in OCP cluster "**provider:** ocp" ? , if yes ,, please share the

 

kindly check the attached images 

![1](https://user-images.githubusercontent.com/50797995/150813478-11c6d485-ac38-4cb0-ae77-51c5faebf550.PNG)
![2](https://user-images.githubusercontent.com/50797995/150813483-31b2ab0b-5382-4b92-9b14-52bd42ae5232.PNG)

**Comment by kaovilai** [comment]
@gammohamed You can use [follow this guide](https://github.com/kaovilai/oadp-operator/blob/blog/blogs/oadp-odf/oadp-blog.md) to see how you can use local object storage. Generally, you would use provider: aws with a custom s3url to a local destination to object storage available locally.
