### ISSUE TITLE
Bug: Use OADP 0.56 to backup and restore, failed to back a postgres pod, with 'volume was empty so no snapshot was taken'

### ISSUE THREAD

**Issue by nanmor** [openshift/oadp-operator#577]
### Contact Details

nanmor@126.com

### Describe bug

Hello，
I have an openshift4.9 environment, and OADP 0.5.6 installed. When I try to backup a namespace resource with restic, it always said the postgres volume is empty. I'm sure data is in there. I don't know what's wrong with that．
Please help to check, thanks a lot.

### What happened?

There is no error in backup log, but in restic instance log:
  completionTimestamp: '2022-02-23T08:18:36Z'
  message: volume was empty so no snapshot was taken
  path: >-
    /host_pods/9193b3c7-dd29-4767-9332-1168e9b5bdd5/volumes/kubernetes.io~nfs/pvc-4bc2a706-5c8d-42b2-b20a-bb78b2c07d11
  phase: Completed
  progress: {}
Storage: nfs

### OADP Version

0.5.x (Stable)

### OpenShift Version

4.9

### New issue

- [X] This issue is new

**Comment by kaovilai** [comment]
We would need more log to be able to dig more into this.

**Comment by kaovilai** [comment]
Could you write repeatable steps covering
1. application deployment
2. backup steps, ie how did you initiate backup
3. which log to look at.

**Comment by nanmor** [comment]
fine, my steps:
1. install minio and create a bucket
2. install OADP from openshift market 
3. create a DataProtectionApplication
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  creationTimestamp: '2022-02-20T15:33:49Z'
  generation: 2
  managedFields:
    - apiVersion: oadp.openshift.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:backupLocations': {}
          'f:configuration':
            .: {}
            'f:restic':
              .: {}
              'f:enable': {}
            'f:velero':
              .: {}
              'f:defaultPlugins': {}
      manager: Mozilla
      operation: Update
      time: '2022-02-20T15:33:49Z'
    - apiVersion: oadp.openshift.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
      manager: manager
      operation: Update
      subresource: status
      time: '2022-02-20T15:33:50Z'
  name: velero-sample
  namespace: oadp-operator
  resourceVersion: '3989880'
  uid: 7866849a-2d70-45e1-a023-97fead6d5cad
spec:
  backupLocations:
    - velero:
        config:
          region: minio
          s3ForcePathStyle: 'true'
          s3Url: 'http://minio-velero.apps.amp-fb'
        credential:
          key: cloud
          name: cloud-credentials
        default: true
        objectStorage:
          bucket: velero
          prefix: cpdbackup
        provider: aws
  configuration:
    restic:
      enable: true
    velero:
      defaultPlugins:
        - openshift
        - aws
        - csi
status:
  conditions:
    - lastTransitionTime: '2022-02-20T15:36:40Z'
      message: Reconcile complete
      reason: Complete
      status: 'True'
      type: Reconciled
4. wait all pods ready
5. install our operator and waiting all things ready, add some data, it include a vault, keycloak and postgres
6. In the OADP operator create a backup instance 
    apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/source-cluster-k8s-gitversion: v1.22.3+e790d7f
    velero.io/source-cluster-k8s-major-version: '1'
    velero.io/source-cluster-k8s-minor-version: '22'
  resourceVersion: '4394971'
  name: myntest
  uid: fe86e939-b3d5-4f66-bb52-1b5c0ad27bfa
  creationTimestamp: '2022-02-21T02:48:49Z'
  generation: 8
  managedFields:
    - apiVersion: velero.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:defaultVolumesToRestic': {}
          'f:includedNamespaces': {}
          'f:storageLocation': {}
      manager: Mozilla
      operation: Update
      time: '2022-02-21T02:48:49Z'
    - apiVersion: velero.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:velero.io/source-cluster-k8s-gitversion': {}
            'f:velero.io/source-cluster-k8s-major-version': {}
            'f:velero.io/source-cluster-k8s-minor-version': {}
          'f:labels':
            .: {}
            'f:velero.io/storage-location': {}
        'f:spec':
          'f:ttl': {}
        'f:status':
          .: {}
          'f:completionTimestamp': {}
          'f:expiration': {}
          'f:formatVersion': {}
          'f:phase': {}
          'f:progress':
            .: {}
            'f:itemsBackedUp': {}
            'f:totalItems': {}
          'f:startTimestamp': {}
          'f:version': {}
      manager: velero-server
      operation: Update
      time: '2022-02-21T02:49:19Z'
  namespace: oadp-operator
  labels:
    velero.io/storage-location: velero-sample-1
spec:
  defaultVolumesToRestic: true
  includedNamespaces:
    - myn-test
  storageLocation: velero-sample-1
  ttl: 720h0m0s
status:
  completionTimestamp: '2022-02-21T02:49:19Z'
  expiration: '2022-03-23T02:48:49Z'
  formatVersion: 1.1.0
  phase: Completed
  progress:
    itemsBackedUp: 159
    totalItems: 159
  startTimestamp: '2022-02-21T02:48:49Z'
  version: 1
it created three restic backup instance for our three pvs
others: 
  completionTimestamp: '2022-02-21T02:49:14Z'
  path: >-
    /host_pods/488776fb-3ab7-452f-adcf-698f6a40b5bb/volumes/kubernetes.io~nfs/pvc-4f9706ef-a733-4e0b-81ab-c5319a314702
  phase: Completed
  progress: {}
  snapshotID: ba5bb500
  startTimestamp: '2022-02-21T02:49:12Z'

status:
  completionTimestamp: '2022-02-21T02:49:12Z'
  path: >-
    /host_pods/864f0a2a-6bff-4216-a3bc-db41dfe63c22/volumes/kubernetes.io~nfs/pvc-62b677dc-488e-4007-8e5b-375c5dbb7d73
  phase: Completed
  progress:
    bytesDone: 3902
    totalBytes: 3902
  snapshotID: 8e576f1d
  startTimestamp: '2022-02-21T02:49:10Z'

but for postgres:
apiVersion: velero.io/v1
kind: PodVolumeBackup
metadata:
  generateName: myntest-
  annotations:
    velero.io/pvc-name: merlin-postgresql-claim
  resourceVersion: '4394943'
  name: myntest-hbfqv
  uid: 36697af5-b2f5-4e34-a55d-a032a7a810b2
  creationTimestamp: '2022-02-21T02:49:15Z'
  generation: 3
  managedFields:
    - apiVersion: velero.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:velero.io/pvc-name': {}
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:velero.io/backup-name': {}
            'f:velero.io/backup-uid': {}
            'f:velero.io/pvc-uid': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"fe86e939-b3d5-4f66-bb52-1b5c0ad27bfa"}': {}
        'f:spec':
          .: {}
          'f:backupStorageLocation': {}
          'f:node': {}
          'f:pod':
            .: {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
            'f:uid': {}
          'f:repoIdentifier': {}
          'f:tags':
            .: {}
            'f:backup': {}
            'f:backup-uid': {}
            'f:ns': {}
            'f:pod': {}
            'f:pod-uid': {}
            'f:pvc-uid': {}
            'f:volume': {}
          'f:volume': {}
        'f:status':
          .: {}
          'f:progress': {}
      manager: velero-server
      operation: Update
      time: '2022-02-21T02:49:15Z'
    - apiVersion: velero.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:completionTimestamp': {}
          'f:message': {}
          'f:path': {}
          'f:phase': {}
          'f:startTimestamp': {}
      manager: restic-server
      operation: Update
      time: '2022-02-21T02:49:17Z'
  namespace: oadp-operator
  ownerReferences:
    - apiVersion: velero.io/v1
      controller: true
      kind: Backup
      name: myntest
      uid: fe86e939-b3d5-4f66-bb52-1b5c0ad27bfa
  labels:
    velero.io/backup-name: myntest
    velero.io/backup-uid: fe86e939-b3d5-4f66-bb52-1b5c0ad27bfa
    velero.io/pvc-uid: edddde4b-2fb1-4316-80da-74384db43798
spec:
  backupStorageLocation: velero-sample-1
  node: worker-0
  pod:
    kind: Pod
    name: postgres-0
    namespace: myn-test
    uid: 7ae781d4-c7d4-47e6-b0a3-de28f4d35eb3
  repoIdentifier: >-
    s3:http://minio-velero.apps.amp-fb/velero/cpdbackup/restic/myn-test
  tags:
    backup: myntest
    backup-uid: fe86e939-b3d5-4f66-bb52-1b5c0ad27bfa
    ns: myn-test
    pod: postgres-0
    pod-uid: 7ae781d4-c7d4-47e6-b0a3-de28f4d35eb3
    pvc-uid: edddde4b-2fb1-4316-80da-74384db43798
    volume: my-postgresql-claim
  volume: my-postgresql-claim
status:
  completionTimestamp: '2022-02-21T02:49:17Z'
  message: volume was empty so no snapshot was taken
  path: >-
    /host_pods/7ae781d4-c7d4-47e6-b0a3-de28f4d35eb3/volumes/kubernetes.io~nfs/pvc-edddde4b-2fb1-4316-80da-74384db43798
  phase: Completed
  progress: {}
  startTimestamp: '2022-02-21T02:49:15Z'

7. delete the operator, and created a restore for that, it could restore but no data in there.

**Comment by nanmor** [comment]
I did a same test again, the same postgres pv failed with same error in restic backup log:
status:
  completionTimestamp: '2022-02-24T09:52:19Z'
  message: volume was empty so no snapshot was taken
  path: >-
    /host_pods/1950f55b-1e43-48c8-b049-f8292ed4cb2d/volumes/kubernetes.io~nfs/pvc-e0075e9e-22ed-43dd-bb48-11ad24252f8f
  phase: Completed
  progress: {}
  startTimestamp: '2022-02-24T09:52:18Z'
I checked the restic daemonset pod , it have this volume and not empty
sh-4.4# ls -lar 
total 4
drwxrwxrwx. 3 nobody nobody 4096 Feb 24 08:42 pvc-e0075e9e-22ed-43dd-bb48-11ad24252f8f
drwxr-x---. 6 root   root    121 Feb 24 09:26 ..
drwxr-x---. 3 root   root     54 Feb 24 09:26 .

for another PV which is used for engine, it backup with no error:
status:
  completionTimestamp: '2022-02-24T09:52:16Z'
  path: >-
    /host_pods/2ceb24bd-64b7-44ed-8323-94cc587634ce/volumes/kubernetes.io~nfs/pvc-07b51b68-177b-4495-b090-9ec4e22fd511
  phase: Completed
  progress:
    bytesDone: 3129
    totalBytes: 3129
  snapshotID: 2264c00b
  startTimestamp: '2022-02-24T09:52:13Z'
they are in the same operator and used same storage class, 
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-storage-provisioner
  uid: 87aa7f1e-f2cb-4679-b6f3-69981ffc6935
  resourceVersion: '25847'
  creationTimestamp: '2022-02-22T04:23:41Z'
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
  managedFields:
    - manager: kubectl-annotate
      operation: Update
      apiVersion: storage.k8s.io/v1
      time: '2022-02-22T04:23:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:storageclass.kubernetes.io/is-default-class': {}
    - manager: kubectl-create
      operation: Update
      apiVersion: storage.k8s.io/v1
      time: '2022-02-22T04:23:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:parameters':
          .: {}
          'f:archiveOnDelete': {}
        'f:provisioner': {}
        'f:reclaimPolicy': {}
        'f:volumeBindingMode': {}
provisioner: nfs-storage
parameters:
  archiveOnDelete: 'false'
reclaimPolicy: Delete
volumeBindingMode: Immediate

For the their PVC:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pvc-e0075e9e-22ed-43dd-bb48-11ad24252f8f
  storageClassName: nfs-storage-provisioner
  volumeMode: Filesystem

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pvc-07b51b68-177b-4495-b090-9ec4e22fd511
  storageClassName: nfs-storage-provisioner
  volumeMode: Filesystem

our oc is based on Linux alphabore.rch.stglabs.ibm.com 4.18.0-193.el8.ppc64le #1 SMP Fri Mar 27 14:40:12 UTC 2020 ppc64le ppc64le ppc64le GNU/Linux
and the nfs server is the same one.

Please help, thanks a lot.

**Comment by kaovilai** [comment]
> install our operator and waiting all things ready, add some data, it include a vault, keycloak and postgres

Any chance you have those details for me? Like is this something from operator hub?

**Comment by kaovilai** [comment]
Or is it your own set of YAML manifests?

**Comment by kaovilai** [comment]
According to https://github.com/vmware-tanzu/velero/issues/4700 this was resolved.. so closing for now.
