### ISSUE TITLE
Bug: mysql in tests/e2e is an empty database... no data, no app

### ISSUE THREAD

**Issue by weshayutin** [openshift/oadp-operator#609]
### Contact Details

whayutin@redhat.com

### Describe bug

A bug happened when I ate cereal!  <--- TIGER?

https://github.com/openshift/oadp-operator/blob/master/tests/e2e/sample-applications/mysql-persistent/mysql-persistent-template.yaml 

was meant to replace 

https://github.com/openshift/oadp-operator/blob/master/tests/e2e/sample-applications/mssql-persistent/mssql-persistent-template.yaml

However... now we just deploy an empty mysql db and backup and restore that?
I think we need an app + data for the full replacement.

### What happened?

Nothing.. no data.. :)

### OADP Version

1.0.1 (Stable)

### OpenShift Version

4.9

### New issue

- [X] This issue is new

**Comment by weshayutin** [comment]
Current setup is empty..

```
sh-4.4$ mysql --user=root
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 12
Server version: 8.0.26 Source distribution

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| MYSQL_DATABASE     |
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
5 rows in set (0.01 sec)

mysql> use MYSQL_DATABASE;
Database changed
mysql> show tables;
Empty set (0.00 sec)

mysql> 
```

**Comment by weshayutin** [comment]
Changing gears on this issue...  mediawiki is not a great sample app.
A more user friendly mariadb / mysql app is a better idea.

I have everything done minus one issue.  See details here:
https://github.com/weshayutin/todolist-mariadb-go/issues/1

**Comment by kaovilai** [comment]
We have added data to database in e2e.
