### ISSUE TITLE
Bug: Restoring image stream failed since admission webhook

### ISSUE THREAD

**Issue by Frank51** [openshift/oadp-operator#632]
### Contact Details

yunqian.chen@dell.com

### Describe bug

In an environment of OADP 0.4.2, when restoring a namespace using velero, the log shows imagestreams restoration is failed.

### What happened?

In an environment of OADP 0.4.2, when restoring a namespace using velero, the log shows imagestreams restoration is failed.

### OADP Version

0.4.x (Beta)

### OpenShift Version

4.6

### Velero pod logs

```shell
Restoring MetadataUnable to restore namespace 'paal-dev' using Velero. {"namespaces":{"testrestoreall":["error restoring configurations.serving.knative.dev/testrestoreall/hello-world: admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: missing field(s): metadata.labels.serving.knative.dev/service","error restoring imagestreams.image.openshift.io/testrestoreall/buildtest: ImageStream.image.openshift.io \"buildtest\" is invalid: []: Internal error: imagestreams \"buildtest\" is invalid: spec.tags[latest].from.name: Invalid value: \"buildtest@sha256:8189cef4b9d60cb3f80ecc017dc0ea160526fde8f0c1a36e956e3b30c981c3f3\": error generating tag event: imagestreamimage.image.openshift.io \"sha256:8189cef4b9d60cb3f80ecc017dc0ea160526fde8f0c1a36e956e3b30c981c3f3\" not found","error restoring ingresses.networking.internal.knative.dev/testrestoreall/hello-world: admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: service namespace
```

### New issue

- [X] This issue is new

**Comment by kaovilai** [comment]
Similar to https://github.com/openshift/oadp-operator/issues/538
These are caused by validation.webhook.serving.knative.dev.

**Comment by kaovilai** [comment]
This issue will be resolved when https://github.com/knative/serving/issues/10926 is resolved.

Not a bug in oadp implementation.

**Comment by kaovilai** [comment]
@Frank51 
> validation failed: missing field(s): metadata.labels.serving.knative.dev/service

I wonder if just filling this field out prior to backup would solve the problem at restore time.

**Comment by kaovilai** [comment]
Routes and Configuration restore issues maybe due to missing labels required at backup time

> Any changes to specifications, metadata labels, or metadata annotations for a Service must be copied to the Route and Configuration owned by that Service. The serving.knative.dev/service label on the Route and Configuration must also be set to the name of the Service. Any additional labels or annotations on the Route and Configuration not specified earlier must be removed.
> 
> The Service updates its status fields based on the corresponding status value for the owned Route and Configuration. The Service must include conditions ofRoutesReady and ConfigurationsReady in addition to the generic Ready condition. Other conditions can also be present.

https://knative.dev/docs/serving/services/#modifying-knative-services

**Comment by kaovilai** [comment]
Routes restore errors maybe in addition caused by https://github.com/openshift/openshift-velero-plugin/issues/129
