### ISSUE TITLE
How do you add the debug flag to Velero?

### ISSUE THREAD

**Issue by tormig-softronic** [openshift/oadp-operator#635]
If you add:
  - --log-level 
  - debug 
to args: in the deployment of Velero it gets instantly removed by the oprator and you cannot add it to the running pod. If you try to add it to the DataProtectionApplications configuration it's just ignored.

We have an issue with Velero and maybe we could get some more info with the debug flag on.

We are running Openshift 4.8 with the OADP Operator 1.0.2 which has deployed Velero v1.7.1-OADP

**Comment by kaovilai** [comment]
This is expected. With OADP operator running, you can expect operator to be continually ensure that Velero deployment is configured as per what DataProtectionApplication defined.

We have added the ability to specify loglevel recently https://github.com/openshift/oadp-operator/pull/588 but it is unreleased. You should see it when we release either 1.0.3 or 1.1 next.

For the time being, when operator has reconciled DataProtectionApplication, you can reduce the _openshift-adp-controller-manager_ replicas to zero. Then you can make changes to Velero custom resource without _openshift-adp-controller-manager_ overwriting your changes.

When you need _openshift-adp-controller-manager_ to process your DPA again, you can set replicas to 1.
