### ISSUE TITLE
Bug: Inaccessible url in docs at https://oadp.konveyor.io

### ISSUE THREAD

**Issue by lebrisg** [openshift/oadp-operator#661]
### Contact Details

lebrisg@hotmail.com

### Describe bug

OADP documentation at https://oadp.konveyor.io points to inaccessible urls at https://gitlab.consulting.redhat.com (https://oadp.konveyor.io/examples/stateless & https://oadp.konveyor.io/examples/stateful)
Example deployments are impossible without Red Hat credentials.

### What happened?

It is not possible to deploy OADP examples to test it.

### OADP Version

1.0.1 (Stable)

### OpenShift Version

4.10

### New issue

- [X] This issue is new

**Comment by kaovilai** [comment]
Fyi please use https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html-single/backup_and_restore/index

The information on the konveyor.io site are pre 1.0 and are not supported.

We'll get the site redirects updated. Thanks!

**Comment by dymurray** [comment]
@lebrisg can you tell us where you found the reference to `oadp.konveyor.io` so we can get it removed?

**Comment by lebrisg** [comment]
I found the reference to oadp.konveyor.io in the OpenShift OADP operator details page.

**Comment by rayfordj** [comment]
Thanks, @lebrisg!

@dymurray , While it appears to have been corrected [here](https://github.com/openshift/oadp-operator/blob/oadp-1.0/bundle/manifests/oadp-operator.clusterserviceversion.yaml#L598), it remains in the downstream CSV template that creates OADP's CSV.

```
  links:
  - name: OADP Operator
    url: https://oadp.konveyor.io/
  maintainers:
  - email: dymurray@redhat.com
```

**Comment by rayfordj** [comment]
@dymurray , do we need (or already have) a Jira issue to track this for QE verification?
