### ISSUE TITLE
Bug: The OADP should have an organization in quay w/ multiple owners where sample-app containers can be pushed and used in CI

### ISSUE THREAD

**Issue by weshayutin** [openshift/oadp-operator#666]
### Contact Details

whayutin@redhat.com

### Describe bug

The sample-apps we're using in tests/e2e will start to support multi-arch builds which require multi-arch manifests and pushed as a single container manifest into quay.  FYI.. it appears to that one container is present, however multiple arches are supported.  

The source code for the sample-apps and the manifests should be present in https://github.com/konveyor/mig-demo-apps  

Ideally we also create ci directly on the mig-demo-apps repo so we can be sure things will work properly w/o OADP or other projects failing.

### What happened?

We're going multi-arch baby

### OADP Version

1.0.1 (Stable)

### OpenShift Version

4.10

### New issue

- [X] This issue is new

**Comment by kaovilai** [comment]
If we do source to image, we won't need this.
Alternative to quay we can also use github container registry ghcr.io which publishes packages to https://github.com/orgs/konveyor/packages

**Comment by Mathieu-Ferraton** [comment]
@weshayutin @kaovilai We are now using this quay.io/migqe repo to store multi-arch images used in the downstream CI. Maybe we can push upstream CI app images there as well. What do you think?

**Comment by kaovilai** [comment]
Sounds good to me.
