### ISSUE TITLE
Bug: All master upstream e2e CI is failing on  MySQL application NoDefaultBackupStorageLocation

### ISSUE THREAD

**Issue by weshayutin** [openshift/oadp-operator#709]
### Contact Details

hitpatel@redhat.com

### Describe bug

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-oadp-operator-master-4.10-operator-e2e-aws-periodic-slack/1529311436629610496/artifacts/operator-e2e-aws-periodic-slack/e2e/build-log.txt

2022/05/25 05:02:58 Waiting for velero pod to be running
I0525 05:05:59.989947   11531 request.go:665] Waited for 1.042461501s due to client-side throttling, not priority and fairness, request: GET:https://api.ci-op-mt2v761l-84046.origin-ci-int-aws.dev.rhcloud.com:6443/apis/helm.openshift.io/v1beta1?timeout=32s
2022/05/25 05:06:01 Printing events for namespace:  openshift-adp
2022/05/25 05:06:01 Running must gather for failed test - MySQL application NoDefaultBackupStorageLocation
[38;5;9m• [FAILED] [187.699 seconds][0m
AWS backup restore tests
[38;5;243m/go/src/github.com/openshift/oadp-operator/tests/e2e/backup_restore_suite_test.go:21[0m
  backup and restore applications
  [38;5;243m/go/src/github.com/openshift/oadp-operator/tests/e2e/backup_restore_suite_test.go:87[0m
    [38;5;9m[1m[It] MySQL application NoDefaultBackupStorageLocation[0m
    [38;5;243m/go/src/github.com/openshift/oadp-operator/tests/e2e/backup_restore_suite_test.go:269[0m

  [38;5;243mBegin Captured GinkgoWriter Output >>[0m
    velero pods not found
    velero pods not found
    velero pods not found
    velero pods not found
    velero pods not found
    velero pods not found
    velero pods not found
    velero pods not found
    velero pods not found
    velero pods not found
    velero pods not found
    velero pods not found

### What happened?

4,7 - 4.10 e2e tests failing:
[link to ci results](http://oadp-ci.usersys.redhat.com:8080/d/x6y6_EU7k/oadp-periodic?orgId=1&var-influxdb_filter=job_name%7C%3D~%7C%2F.*master.*%2F)

### OADP Version

Unreleased (built from source)

### OpenShift Version

4.10

### New issue

- [X] This issue is new

**Comment by weshayutin** [comment]
Update the ISSUE TIGER!!!! https://github.com/openshift/oadp-operator/pull/710

**Comment by kaovilai** [comment]
Just ✅  wait ✅  till ✅  you ✅ see ✅ beautiful ✅ green ✅  ticks.

**Comment by kaovilai** [comment]
Closed by #717
