### ISSUE TITLE
Bug: OKD operatorhub only offers old version 0.5.6

### ISSUE THREAD

**Issue by ibotty** [openshift/oadp-operator#722]
### Describe bug

Operatorhub on OKD only offers the following versions:
 * beta stream: oadp-operator.v0.4.2
 * stable stream: oadp-operator.v0.5.6
I'd like to use the stable(-sounding) release 1.0.x.

### What happened?

The old version gets installed.

### OADP Version

0.5.x (Stable)

### New issue

- [X] This issue is new

**Comment by kaovilai** [comment]
We do not support usage of OADP on OKD officially.

You may choose to [install OADP by building from source.](https://github.com/openshift/oadp-operator/blob/master/docs/developer/install_from_source.md)

If the instruction doesn't work for you let us know.

**Comment by ibotty** [comment]
This is unfortunate and your comment is not only slightly disappointing.

**Comment by kaovilai** [comment]
To the best of my knowledge there are still people using the community version. We still want to provide path for people to update to the latest community version 0.5.6 which are compatible with 1.0.0 on the supported OpenShift cluster.
