### ISSUE TITLE
Bug: x509: certificate signed by unknown authority in oadp-aws-registry pod

### ISSUE THREAD

**Issue by rh-aj** [openshift/oadp-operator#742]
### Describe bug

Hello,

I can't reopen #351 so I open this issue as I can not manage to make self-signed certificates work.
Just like @gorantornqvist the aws registry won't start due to unknown authority.

I have a Root CA & Intermediate certificate. I tried every combination I could think of (root+intermediate, intermediate+root, root only, intermediate only). Everything base64-ed.

Setting insecureSkipTLSVerify to true makes the Pod start, but as its name suggests, it's insecure :)

After checking code, I can't see "caCert" mentionned anywhere except in the docs. Is it implemented ?

Sorry I can't copy/paste logs because I'm using a VM provided by my client.

oc logs oadp-test-1-aws-registry-xxx
... s3aws: RequestError: send request failed ... x509: certificate signed by unknown authority ...

Do you have any idea ? Did I miss something ?

Thanks.

### What happened?

I expected that the aws registry Pod starts and works.

### OADP Version

1.0.1 (Stable)

### OpenShift Version

4.10

### New issue

- [X] This issue is new

**Comment by rh-aj** [comment]
Hi,

The S3 had a bad certificate, that's why it was not working...

I now understand that the caCert field is passed directly to velero so I should have opened the issue on velero project.

Sorry for the noise,
Regards,

**Comment by kaovilai** [comment]
Hey @rh-aj, the issue you are encountering is an OADP specific issue. Not velero project. Enhancement to support caCert with registry backup is planned. For the moment you can avoid this issue by setting dpa spec like so.
```yaml
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: example
spec:
  backupImages: false
```

**Comment by kaovilai** [comment]
Tracking registry support of self-singed certificate here https://issues.redhat.com/browse/OADP-641
