### ISSUE TITLE
E2E test failures for Mongo application Backup/restore suite

### ISSUE THREAD

**Issue by hhpatel14** [openshift/oadp-operator#754]
### Describe bug

 E2E tests are failing for master branch. https://prow.ci.openshift.org/?type=periodic&job=*oadp-operator-master*

### What happened?

Waiting for app builds to be ready after RESTORE (only for Mongo application)

### OADP Version

1.0.2 (Stable)

### New issue

- [X] This issue is new

**Comment by kaovilai** [comment]
closed with https://github.com/openshift/openshift-velero-plugin/pull/155
