### ISSUE TITLE
Bug: velero metrics stripped

### ISSUE THREAD

**Issue by felicianmv** [openshift/oadp-operator#769]
### Contact Details

felician.moldovan@flex.com

### Describe bug

Hi guys,

I'm trying to setup alerting and reporting for our OADP instance ( 1.0.3 ) and Prometheus/Grafana is the logical solution, but from what I see data related to Velero are only 2: velero_backup_total and velero_restore_total.

Checking upstream Velero docs and /metrics URL shows that Velero actually is exposing a lot more data ( vanila_metrics.txt attached ), but Prometheus doesn't pick them up.
[vanilla_metrics.txt](https://github.com/openshift/oadp-operator/files/9180866/vanilla_metrics.txt)

On the OADP namespace I found a ServiceMonitor object ( openshift-adp-velero-metrics-sm ) which seems to be filtering data recorded by Prometheus, specifically this section:
`
   metricRelabelings:
    - action: keep
      regex: velero_backup|velero_restore
      sourceLabels:
      - __name__
`

I changed the above section into 
`
   metricRelabelings:
    - action: keep
      regex: velero_backup.*|velero_restore.*
      sourceLabels:
      - __name__
`
and now I have all the data to setup monitoring.

### What happened?

Is there a specific reason for that filter in the ServiceMonitor?
Is it fine to use my solution above for production?
Any plans to remove the filter in a future version of OADP?

### OADP Version

1.0.3 (Stable)

### OpenShift Version

4.8

### New issue

- [X] This issue is new

**Comment by shubham-pampattiwar** [comment]
@felicianmv Thank you for reaching out and raising the concerns. We added a service monitor to filter out the metrics exposed  via Velero because most of the metrics exposed did not have bounded [cardiniality](https://www.robustperception.io/cardinality-is-key/) and we were concerned that this might affect openshift's in-cluster monitoring stack adversely.

**Comment by QuingKhaos** [comment]
@shubham-pampattiwar Can we please have a `exposeAllMetrice: true` setting on the operator, so we can override this as long as we are aware of the cardinality consequences? We need to create alerts on production backup schedules.

**Comment by kaovilai** [comment]
> Do not check teh Enable Monitoring checkbox during installation of OADP Operator

Then you can have your own prometheus instance record everything.
