### ISSUE TITLE
Downstream Docs: Provider minimum permissions for internal image backup

### ISSUE THREAD

**Issue by maratsal** [openshift/oadp-operator#776]
### Contact Details

marat@arctiq.ca

### Describe bug

Missing permissions for the policy to be able to backup images and image streams.
Documentation for OADP deployment with S3 backed storage from AWS - https://docs.openshift.com/container-platform/4.10/backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.html#migration-configuring-aws-s3_installing-oadp-aws

### What happened?

Images and imagestreams cannot be backed up because of the permission issues.

The fix would be to add additional permissions `"s3:ListBucketMultipartUploads"` to the section below:
```
      {
         "Effect":"Allow",
         "Action":[
            "s3:ListBucket",
            "s3:ListBucketMultipartUploads"
         ],
         "Resource":"arn:aws:s3:::${BUCKET}"
      },
```

### OADP Version

1.0.3 (Stable)

### OpenShift Version

4.10

### Velero pod logs

```shell
time="2022-07-28T15:54:29.750804396Z" level=error msg="error resolving upload: s3aws: AccessDenied: Access Denied\n\tstatus code: 403, request id: 36Z9K5GADB4886WW, host id: H8byEXe+vF1xIFRfuULtzh55/SuEK8sk1xcgbdfgbefgbKJYFGYJG6Ti22qvELsXWeQt4=" go.version=go1.13.4 http.request.contenttype=application/octet-stream http.request.host=oadp-velero-1-aws-registry-route-openshift-adp.apps.mycluster.mydomain.com http.request.id=c27547c6-697a-4ba1-b33c-119281f11a07 http.request.method=PATCH http.request.remoteaddr=192.168.67.242 http.request.uri="/v2/my-nice-project/test-2/blobs/uploads/40ba8729-59f1-4789-8a59-63c7c6940814?_state=kiRZX6kMPbkxnDR8W9UxnvsfhnbehnndhJHGJYfukgFwLWRldi90ZXN0LTIiLCJVVUlEIjoiNDBiYTg3MjktNTlmMS00Nzg5LThhNTktNjNjN2M2OTQwODE0IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIyLTA3LTI4VDE1OjU0OjI5LjIwNTM0MzMzMVoifQ%3D%3D" http.request.useragent="containers/5.19.0 (github.com/containers/image)" vars.name=my-nice-project/test-2 vars.uuid=40ba8729-59f1-4789-8a59-63c7c6940814
```

### Restic pod logs

```shell
N/A
```

### Operator pod logs

```shell
N/A
```

### New issue

- [X] This issue is new

**Comment by kaovilai** [comment]
We are aware. Issue is being worked on and tracked at https://issues.redhat.com/browse/OADP-419

**Comment by kaovilai** [comment]
https://issues.redhat.com/browse/OADP-419 was closed.
