### ISSUE TITLE
Support AWS IAM roles annotations

### ISSUE THREAD

**Issue by dav1dli** [openshift/oadp-operator#79]
Please enable scenario described here: https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html . It was tested to be functional using Velero Helm chart https://github.com/vmware-tanzu/helm-charts/tree/master/charts/velero by using option "useSecret: false" and annotating service account with "eks.amazonaws.com/role-arn: 'arn:aws:iam::ACCOUNT:role/ROLE'" , where the role is set in AWS with required permissions. This enables real life scenario when AWS credentials are not provided statically.

Current behaviour is if a secret with AWS credentials is not provided velero server fails to instantiate in preflight.yaml.

**Comment by dymurray** [comment]
Thanks for bringing this to our attention, this is certainly a bug that we will address.

**Comment by dymurray** [comment]
https://github.com/openshift/oadp-operator/issues/175
