### ISSUE TITLE
Bug: Alertmanager throwing warning about generation mismatch

### ISSUE THREAD

**Issue by knutejohKLP** [openshift/oadp-operator#847]
### Describe bug

Alertmanager is sending out warnings from all our clusters for openshift-adp/velero, stating the following:

description = Deployment generation for openshift-adp/velero does not match, this indicates that the Deployment has failed but has not been rolled back.
summary = Deployment generation mismatch due to possible roll-back

But we can't see that any rollback has happened or any means to fix the warning. We could always silence the alarm, but I would rather fix the issue. We are running OpenShift 4.10.33, 4.10.17 with OADP version oadp-operator.v1.1.0

### What happened?

Alarms are coming from AlertManager

### OADP Version

1.0.3 (Stable)

### OpenShift Version

4.10

### New issue

- [X] This issue is new

**Comment by knutejohKLP** [comment]
We upgraded to OADP 1.1, and the issue still remains. We see in the logs that the generation is being constantly updated which is probably the reason for the alert to kick off.  #634 Seems to state the exact same issues with the generation being updated and the deployment being reconciled all the time, but that issue is closed. Are the fixes for that issue in OADP 1.1? And if so, is this a similar bug to #634?

**Comment by kaovilai** [comment]
@knutejohKLP please wait for https://issues.redhat.com//browse/OADP-812 to move to resolve status.
