### ISSUE TITLE
OADP-926: data mover as optional on backup specification

### ISSUE THREAD

**Issue by davidriosdelgado** [openshift/oadp-operator#849]
**Is your feature request related to a problem? Please describe.**
When data mover is enabled in the dpa configuration, I don´t see how to exclude some CSI backups out of the data mover workflow. That means every snapshot executed by velero, is exported to the S3 bucket and by this, there is unnecessary net traffic generated and s3 space consumed, when only a recovery point provided by the snapshot instead of the full copy. 

**Describe the solution you'd like**
As restic is optional in the backup yaml specification, I would like to see datamover as an option:

'''
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: <backup>
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  defaultVolumesToRestic: false
  defaultVolumesToDataMover: true
'''

**Describe alternatives you've considered**

- Deploy another DPA instance with Datamover feture disable, however looks like this doesn´t work because issues with the configmap "restic-restore-action-config" and its ownership from the first dpa instance.

**Additional context**

**Comment by shubham-pampattiwar** [comment]
@davidriosdelgado Thank you for reaching out. I have a few follow up questions:
1. For a single backup, lets say you have a list of csi pvcs, Do you want to use csi datamover feature for some of them and local csi snapshotting for the remaining ones ?
2. For a single backup, given a list of pvc, Do you want to use csi related workflow (snapshotting or datamovement to s3) for some of them and restic or some other backup mechanism for the remaining ones ?

**Comment by sseago** [comment]
@shubham-pampattiwar if it's data mover for some, restic for others, that's already supported.

**Comment by davidriosdelgado** [comment]
Hello, @shubham-pampattiwar , 

1. Mostly yes.
2. For this, currently we are running two backup jobs, one which restic feature is enabled and a second one which restic is disabled, and because this, it runs a csi snapshot backup type

@sseago does it mean, for the same backup job, is it possible to protect some pvcs with restic and others with csi snapshot? may I ask for an example?

Thanks

**Comment by sseago** [comment]
@davidriosdelgado yes. If you're setting defaultVolumesToRestic to false (the default setting), then you can choose restic on an opt-in basis via pod annotations. If you're setting defaultVolumesToRestic to true, then restic will be the default mode of volume backup, and you can opt-out from restic (to use CSI) again via pod annotations.

The two approaches are described here: https://velero.io/docs/v1.9/restic/#to-back-up

**Comment by davidriosdelgado** [comment]
cool thank you, with that we just need a way to have local snapshots and S3 exported snapshots when data mover is enabled.

**Comment by kaovilai** [comment]
@davidriosdelgado 
> with that we just need a way to have local snapshots and S3 exported snapshots when data mover is enabled.

Are you making a feature request? Can you clarify what you mean here?
restic already put data in s3.
datamover also put data into s3 iiuc.

**Comment by davidriosdelgado** [comment]
@kaovilai , I guess I explained on the first comment, when data mover is enabled, there is no way (or at least I don´t see how to do it) to have local snapshots, only S3 exported snapshots. The feature request is about the capability to have local snapshots which are not exported to s3 and snapshots which are exported to s3 when data mover is enabled.

**Comment by kaovilai** [comment]
It's already possible per @sseago comments.

**Comment by sseago** [comment]
@kaovilai I think we're getting the two difference use cases mixed up here:
1) some volumes backed up to s3 via restic, and others via CSI/Datamover
2) all volumes backed up via CSI plugin, but only some pushed to s3 via Datamover

1) is the case that's already supported. 2) is not currently possible, as I understand it.

**Comment by davidriosdelgado** [comment]
@sseago you are right, we are looking for the second use case, which is not possible today

**Comment by kaovilai** [comment]
Tracked in https://issues.redhat.com/browse/OADP-926
