### ISSUE TITLE
Azure custom role is hardcoded in config

### ISSUE THREAD

**Issue by demon86rm** [openshift/oadp-operator#867]
**Is your feature request related to a problem? Please describe.**
When you follow the steps to install OADP in ARO, at [some point](https://docs.openshift.com/container-platform/4.10/backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.html#:~:text=Create%20a%20custom%20role%20that%20has%20the%20minimum%20required%20permissions%3A) you are requested to create a custom role for Velero with minimum rbacs. It seems that the operator refers only to a custom role which has to be named "Velero", with no option of changing it. The thing is if you're in an azure subscription where someone else has already created a role in the same tenant, but it has different or no permission at all, the OADP won't work as expected.

**Describe the solution you'd like**
I think that it would be sufficient to make the custom role definition as a parameter in order to extend operator customization in a strict environment which could be Azure.

**Comment by demon86rm** [comment]
This is happening when I try to create the role definition:

```
[mplacidi@mplacidi ~]$ AZURE_ROLE=Velero
[mplacidi@mplacidi ~]$ az role definition create --role-definition '{
   "Name": "'$AZURE_ROLE'",
   "Description": "Velero related permissions to perform backups, restores and deletions",
   "Actions": [
       "Microsoft.Compute/disks/read",
       "Microsoft.Compute/disks/write",
       "Microsoft.Compute/disks/endGetAccess/action",
       "Microsoft.Compute/disks/beginGetAccess/action",
       "Microsoft.Compute/snapshots/read",
       "Microsoft.Compute/snapshots/write",
       "Microsoft.Compute/snapshots/delete",
       "Microsoft.Storage/storageAccounts/listkeys/action",
       "Microsoft.Storage/storageAccounts/regeneratekey/action"
   ],
   "AssignableScopes": ["/subscriptions/'$AZURE_SUBSCRIPTION_ID'"]
   }'
**A custom role with the same name already exists in this directory. Use a different name.**
```
This happens when I try to list any role def named Velero i got no results as I might not have sufficient permissions:

```
[mplacidi@mplacidi ~]$ az role definition list --name Velero
[]
```

**Comment by kaovilai** [comment]
See if instructions at https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure are helpful to you as they are presented slightly differently.

I don't believe there is a hard requirement for AZ_ROLE to be exactly `Velero`

**Comment by demon86rm** [comment]
Thanks for the tips, I'll give it a try.
