### ISSUE TITLE
velero backup-location get command shows Unavailable in Phase column

### ISSUE THREAD

**Issue by yipng** [openshift/oadp-operator#89]
backup-location always shows Unavailable in the PHASE field in the velero backup-location get api or command.  
This is due to the physical layout check from the backup storage in Velero where it detected there are more than 3 subdirs.  Velero expects backups, restores and restic subdirs but OADP added images subdir at the top level.  

$ velero backup-location get
NAME    PROVIDER        BUCKET/PREFIX     PHASE           LAST VALIDATED                             ACCESS MODE
default   velero.io/aws    test1                        Unavailable   2021-02-19 15:40:48 -0800 PST   ReadWrite

https://github.com/vmware-tanzu/velero/blob/456eb19668f8da603756353d9179b59b5a7bfa04/pkg/persistence/object_store.go#L150

**Comment by dymurray** [comment]
Thank you for this bug report. Makes sense and should be an easy fix for us.

**Comment by yipng** [comment]
@dymurray Here are the version info:

```
 oc version
Client Version: 4.6.16
Server Version: 4.6.16
Kubernetes Version: v1.19.0+e49167a
```

oadp image version: quay.io/konveyor/oadp-operator:v0.2.6

I was able to reproduce this using the OpenShift internal image registry and also with restic backup.  After I performed a restic backup, I can see there are 4 subdirectories created at the top level of the object bucket:

backups/
docker/
restic/
restores/

Which may explain the reason for the Unavailable status due to the error check here:
 https://github.com/vmware-tanzu/velero/blob/5bd70fd8eef316d220317245e46dc6016c348dce/pkg/persistence/object_store.go#L194
