### ISSUE TITLE
OADP-1.2 OADP datamover plug-in BackupItemAction Progress / Execute implementation

### ISSUE THREAD

**Issue by weshayutin** [openshift/oadp-operator#914]

**Comment by shubham-pampattiwar** [comment]
Fix PR: https://github.com/migtools/velero-plugin-for-vsm/pull/7

**Comment by weshayutin** [comment]
blocked by the oadp-operator needing to be updated w/ crds

**Comment by shubham-pampattiwar** [comment]
Backup V2 Plugin PR merged https://github.com/migtools/velero-plugin-for-vsm/pull/7
