### ISSUE TITLE
Updates for the oadp-operator for 1.2

### ISSUE THREAD

**Issue by weshayutin** [openshift/oadp-operator#919]
- [ ] update crds
- [ ] datamover specific changes
- [ ] server params
- [ ]

**Comment by shubham-pampattiwar** [comment]
Latest status:
- Velero CRDs and upstream changes are updated 
    - https://github.com/openshift/oadp-operator/pull/940 
    - https://github.com/openshift/oadp-operator/pull/929
    - https://github.com/openshift/oadp-operator/pull/917
- Support for new server parameters is merged 
    - https://github.com/openshift/oadp-operator/pull/916
    - https://github.com/openshift/oadp-operator/pull/909
- Datamover CRDs and VSM related changes are also updated
    - https://github.com/openshift/oadp-operator/pull/934
    - https://github.com/openshift/oadp-operator/pull/927
    - https://github.com/openshift/oadp-operator/pull/899
    - https://github.com/openshift/oadp-operator/pull/896
    - https://github.com/openshift/oadp-operator/pull/897

**Comment by weshayutin** [comment]
@shubham-pampattiwar I believe this is done, correct :)
