### ISSUE TITLE
Flakes in  oadp-operator CI on master

### ISSUE THREAD

**Issue by weshayutin** [openshift/oadp-operator#924]
- [ ] mostly working, some flakes
  - [x] #925
  - [x] #960

**Comment by kaovilai** [comment]
Comparing https://prow.ci.openshift.org/pr-history/?org=openshift&repo=oadp-operator&pr=927 and https://prow.ci.openshift.org/pr-history/?org=openshift&repo=oadp-operator&pr=909 I'd say https://github.com/openshift/oadp-operator/issues/924 can close until further notice.
