### ISSUE TITLE
Insecure container registry exposed on the cluster

### ISSUE THREAD

**Issue by alexisph** [openshift/oadp-operator#93]
Hi.
We are testing on an OCP 4.6 disconnected cluster, whether OADP operator can fulfill our backup/restore needs instead of using upstream velero directly.

We've noticed that the operator exposes this url http://oadp-default-aws-registry-route-oadp-operator.apps.$DOMAIN and, besides being HTTP and not HTTPS, we can push anything to this registry. Whatever we push get copied to our S3 endpoint, under the docker folder.

This registry should be secured with HTTPS and authentication.

**Comment by dymurray** [comment]
We will be targeting resolving this in OADP 1.1. For 1.0, if a customer requires the registry to be communicating over port 443, they will need to simply disable image backups until this issue is resolved or the registry dependency is removed entirely.

To do this, on the DPA spec:
```
...
  backupImages: false
```

**Comment by jwmatthews** [comment]
Tracking in JIRA: https://issues.redhat.com/browse/OADP-195

**Comment by kaovilai** [comment]
Closed via #743
