### ISSUE TITLE
get openshift branches in sync w/ velero 1.11

### ISSUE THREAD

**Issue by weshayutin** [openshift/oadp-operator#931]

**Comment by weshayutin** [comment]
@rayfordj fyi

**Comment by weshayutin** [comment]
@sseago sounded like this was done.. right?

**Comment by shubham-pampattiwar** [comment]
I can see `konveyor-1.11` for velero fork at least https://github.com/openshift/velero/tree/konveyor-1.11

**Comment by sseago** [comment]
@weshayutin yes. Everything on the forks is rebased and updated on the oadp-1.2 branch as of today.
