### ISSUE TITLE
ensure branch permissions on new OADP-1.2 branches are ready

### ISSUE THREAD

**Issue by weshayutin** [openshift/oadp-operator#932]

**Comment by hhpatel14** [comment]
https://github.com/openshift/release/pull/38089 
Targeted repositories

Done: 

- [ ] velero-plugin-for-csi

- [ ] velero-plugin-for-aws

- [ ] velero-plugin-for-gcp

- [ ] velero-pluin-for-microsoft-azure

In Progress: 

- [ ] velero https://github.com/openshift/release/pull/38076

**Comment by hhpatel14** [comment]
In Progress: 
- [ ] migtools/velero-plugin-for-vsm
- [ ] migtools/volume-snapshot-mover
- [ ] openshift/openshift-velero-plugin

**Comment by hhpatel14** [comment]
https://github.com/openshift/release/pull/38130

**Comment by weshayutin** [comment]
@hhpatel14 all set here? done it looks like

**Comment by hhpatel14** [comment]
https://github.com/openshift/release/pull/38220
