### ISSUE TITLE
Update the prow ci to build images for 1.2 branches

### ISSUE THREAD

**Issue by weshayutin** [openshift/oadp-operator#942]
branch name oadp-1.2
What's ready as of 4/4
* velero
* velero-plugin-for-aws, gcp, azure, csi
* velero-plugin
* 

Not ready yet
* vsm
* velero-plugin-for-vsm
* oadp-operator

**Comment by shubham-pampattiwar** [comment]
oadp-1.2 branches created for: 
oadp-operator: https://github.com/openshift/oadp-operator/tree/oadp-1.2
volume-snapshot-mover: https://github.com/migtools/volume-snapshot-mover/tree/oadp-1.2
velero-plugin-for-vsm: https://github.com/migtools/velero-plugin-for-vsm/tree/oadp-1.2

**Comment by hhpatel14** [comment]
https://github.com/openshift/release/pull/38089 
Targeted repositories:

- [ ] velero-plugin-for-csi

- [ ] velero-plugin-for-aws

- [ ] velero-plugin-for-gcp

- [ ] velero-pluin-for-microsoft-azure

In Progress: 

- [ ] velero https://github.com/openshift/release/pull/38076

**Comment by hhpatel14** [comment]
https://github.com/openshift/release/blob/master/core-services/image-mirroring/konveyor/mapping_konveyor_latest
