### ISSUE TITLE
Ensure openshift/oadp-operator e2e tests pass on 1.2 branch

### ISSUE THREAD

**Issue by weshayutin** [openshift/oadp-operator#949]

**Comment by weshayutin** [comment]
@hhpatel14 @kaovilai any updates here?

**Comment by kaovilai** [comment]
data mover will be cherrypicked from https://github.com/openshift/oadp-operator/pull/955

**Comment by kaovilai** [comment]
Closed via #955

**Comment by kaovilai** [comment]
My bad.. I meant it will be closed via https://github.com/openshift/oadp-operator/pull/966
