### ISSUE TITLE
OADP restore fails to restore file - resource restore warning: could not restore, Warning: the in-cluster version is different than the backed-up version."

### ISSUE THREAD

**Issue by joyienjoy** [openshift/oadp-operator#950]
**Is your feature request related to a problem? Please describe.**

We are using Openshift OADP v1.1.3 provided by RedHat in a cluster that uses OCP version 4.10.55
We performed an all namespace backup operation which was completed successfully. 
But while performing restoration, there were many files which were not restored, as they were already present in the cluster.

**Describe the solution you'd like**

We should be able to use restore option as a way to take the cluster resource back to the time, when backup was done. 
It should have some flag or check that should allow us to perform a forced restore of even available resources. 

**Describe alternatives you've considered**

Redhat recommends OADP by Redhat for backup/restore of resources. If anyone can suggest, workable alternates are most welcome. 

**Additional context**

The velero logs were throwing the WARNINGS similar to this:
logSource="/remote-source/velero/app/pkg/controller/restore_controller.go:521" restore=openshift-adp/restore-to-9-19pm
time="2023-04-06T16:31:01Z" level=warning msg="Namespace db2u, resource restore warning: could not restore, ConfigMap \"c-amsdev01-db2uconfig\" already exists. Warning: the in-cluster version is different than the backed-up version."

**Documentary Help**

It will of great help, If there is any documentation that could fulfill my requirement.
Contributors/viewers can share any previous threads, if any, that provides solution for this issue.

**Comment by sseago** [comment]
By default, Velero only restores resources that don't already exist in the cluster. That warning just tells you that the cluster already has that resource, so it couldn't create it. The existingResourcePolicy config option does provide a setting which will attempt to patch existing resources that already exist -- this should work for resources that don't have any differences in immutable fields, although if the diff includes immutable fields, then Velero can't do anything about them. Also note that this option still won't truly take the cluster back in time, since restore won't delete things in the cluster that aren't in the backup.

**Comment by joyienjoy** [comment]
@sseago Thanks for the explanation. Need another explanatory help.
While deploying DataProtectionApplication, we have the option to set "backupImages=true". How this flags helps in restore process. And, how this is having a difference in comparison to "snapshotVolumes: true" in Backup process setup.

**Comment by sseago** [comment]
@joyienjoy The two flags are used for completely different resource types. backupImages=true doesn't affect volume backup -- it's used to tell OADP to back up images in your namespaces that are hosted in the openshift internal registry. snapshotVolumes is used to tell OADP to snapshot volumes (via CSI plugin or native volume snapshotter, depending on what you're using).

**Comment by kaovilai** [comment]
I don't see a feature request here.. for 24/7 troubleshooting/bug report
[Open a new support case](https://access.redhat.com/support/cases/#/case/new) for assistance
