### ISSUE TITLE
Add OCP 4.12, 4.13, 4.14 to oadp-1.2, master e2e tests

### ISSUE THREAD

**Issue by kaovilai** [openshift/oadp-operator#967]
Follow up to https://github.com/openshift/oadp-operator/issues/949

https://github.com/openshift/release/pull/42107
https://github.com/openshift/release/pull/42217
https://github.com/openshift/release/pull/41941
https://github.com/openshift/release/pull/41940
https://github.com/openshift/release/pull/42254
https://github.com/openshift/release/pull/42063
https://github.com/openshift/release/pull/39107 -> replaced by https://github.com/openshift/release/pull/43467

**Comment by mateusoliveira43** [comment]
This should be also fixed by https://github.com/openshift/oadp-operator/issues/1227  by adding documentation on which versions should be tested by release branches, like is documented for master branch https://github.com/openshift/oadp-operator/blob/master/docs/developer/PROW_CI.md?plain=1#L60

**Comment by kaovilai** [comment]
4.15 should also be added

**Comment by mateusoliveira43** [comment]
Closing as resolved now that branches have latest OCP versions in E2E tests
